/**
 * seedJobListings.js
 * One-time Firestore seeder for sample job listings.
 *
 * Run: node seedJobListings.js
 * Requires: GOOGLE_APPLICATION_CREDENTIALS env var pointing to service account key
 *   OR run from Cloud Shell where default credentials are available.
 *
 * Creates 20 realistic faith-aligned job listings across categories.
 */

const admin = require("firebase-admin");

// Initialize with default credentials (Cloud Shell or service account)
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();

const sampleJobs = [
  {
    title: "Lead Worship Pastor",
    description: "Seeking a passionate worship leader to guide our 2,000-member congregation in spirit-filled worship. Must have experience leading teams and creating setlists. Seminary degree preferred.",
    category: "worship",
    jobType: "fullTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Atlanta, GA",
    compensationType: "salary",
    salaryMin: 55000,
    salaryMax: 75000,
    salaryPeriod: "yearly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_1",
    employerName: "Elevation Church Atlanta",
    employerType: "church",
  },
  {
    title: "Senior Software Engineer — Faith Tech Startup",
    description: "Join our mission to build technology that serves the global church. We're building a platform connecting churches worldwide. React Native, Node.js, Firebase experience required. Remote-first, prayer-centered culture.",
    category: "technology",
    jobType: "fullTime",
    classification: "christianOrg",
    workArrangement: "remote",
    location: "Remote (US)",
    compensationType: "salary",
    salaryMin: 120000,
    salaryMax: 160000,
    salaryPeriod: "yearly",
    experienceLevel: "senior",
    employerId: "seed_employer_2",
    employerName: "FaithTech Labs",
    employerType: "faithFriendlyCompany",
  },
  {
    title: "Youth Ministry Director",
    description: "Full-time youth director for ages 12-18. Plan events, lead small groups, mentor student leaders. Background check required. Must have heart for Gen Z.",
    category: "youthMinistry",
    jobType: "fullTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Dallas, TX",
    compensationType: "salary",
    salaryMin: 42000,
    salaryMax: 55000,
    salaryPeriod: "yearly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_3",
    employerName: "Gateway Church",
    employerType: "church",
  },
  {
    title: "Christian School Math Teacher",
    description: "Teach Algebra I/II and Geometry at our K-12 Christian academy. Small class sizes, supportive faculty, daily chapel. State teaching certification required.",
    category: "education",
    jobType: "fullTime",
    classification: "christianOrg",
    workArrangement: "onSite",
    location: "Nashville, TN",
    compensationType: "salary",
    salaryMin: 38000,
    salaryMax: 48000,
    salaryPeriod: "yearly",
    experienceLevel: "entryLevel",
    employerId: "seed_employer_4",
    employerName: "Grace Academy",
    employerType: "school",
  },
  {
    title: "Missions Coordinator — East Africa",
    description: "Coordinate short-term and long-term mission teams to Kenya, Uganda, and Tanzania. Fundraising, logistics, team training. 2+ years missions experience required.",
    category: "missions",
    jobType: "fullTime",
    classification: "missionOrg",
    workArrangement: "hybrid",
    location: "Nairobi, Kenya / Remote",
    compensationType: "salary",
    salaryMin: 35000,
    salaryMax: 50000,
    salaryPeriod: "yearly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_5",
    employerName: "African Inland Mission",
    employerType: "ministry",
  },
  {
    title: "Church Graphic Designer",
    description: "Create sermon series artwork, social media content, and event materials. Proficient in Figma, Photoshop, After Effects. Part-time with potential for full-time.",
    category: "creativeArts",
    jobType: "partTime",
    classification: "churchMinistry",
    workArrangement: "hybrid",
    location: "Los Angeles, CA",
    compensationType: "hourly",
    salaryMin: 25,
    salaryMax: 40,
    salaryPeriod: "hourly",
    experienceLevel: "entryLevel",
    employerId: "seed_employer_6",
    employerName: "Mosaic Church LA",
    employerType: "church",
  },
  {
    title: "Executive Pastor / COO",
    description: "Oversee daily operations of a multi-campus church. Staff management, budgeting, strategic planning. MBA or seminary degree with 10+ years leadership experience.",
    category: "pastoralMinistry",
    jobType: "fullTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Houston, TX",
    compensationType: "salary",
    salaryMin: 90000,
    salaryMax: 130000,
    salaryPeriod: "yearly",
    experienceLevel: "executive",
    employerId: "seed_employer_7",
    employerName: "Lakewood Church",
    employerType: "church",
  },
  {
    title: "Christian Content Writer",
    description: "Write devotionals, blog posts, and curriculum for our Bible study app. Strong theology, engaging storytelling. Remote position with flexible hours.",
    category: "writing",
    jobType: "freelance",
    classification: "christianOrg",
    workArrangement: "remote",
    location: "Remote",
    compensationType: "salary",
    salaryMin: 45000,
    salaryMax: 65000,
    salaryPeriod: "yearly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_8",
    employerName: "Faithlife Media",
    employerType: "mediaMinistry",
  },
  {
    title: "Church Sound Engineer",
    description: "Run live audio for Sunday services and events. Experience with Yamaha CL/QL consoles, Dante networking, and in-ear monitoring. Weekend availability required.",
    category: "worship",
    jobType: "partTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Charlotte, NC",
    compensationType: "hourly",
    salaryMin: 20,
    salaryMax: 35,
    salaryPeriod: "hourly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_9",
    employerName: "Transformation Church",
    employerType: "church",
  },
  {
    title: "Nonprofit Development Director",
    description: "Lead fundraising strategy for our anti-trafficking ministry. Major gifts, grant writing, donor relations. $2M annual goal. Faith-driven team.",
    category: "nonprofit",
    jobType: "fullTime",
    classification: "christianOrg",
    workArrangement: "hybrid",
    location: "Washington, DC",
    compensationType: "salary",
    salaryMin: 70000,
    salaryMax: 95000,
    salaryPeriod: "yearly",
    experienceLevel: "senior",
    employerId: "seed_employer_10",
    employerName: "International Justice Mission",
    employerType: "nonprofit",
  },
  {
    title: "Children's Ministry Volunteer Coordinator",
    description: "Recruit, train, and schedule 100+ volunteers for our children's program. Background check management, curriculum planning. Heart for kids required.",
    category: "childrenMinistry",
    jobType: "fullTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Phoenix, AZ",
    compensationType: "salary",
    salaryMin: 35000,
    salaryMax: 45000,
    salaryPeriod: "yearly",
    experienceLevel: "entryLevel",
    employerId: "seed_employer_11",
    employerName: "Christ's Church of the Valley",
    employerType: "church",
  },
  {
    title: "AI/ML Engineer — Biblical Language Processing",
    description: "Build NLP models for ancient Hebrew and Greek text analysis. Help scholars and pastors study Scripture with AI. PhD in computational linguistics preferred.",
    category: "technology",
    jobType: "fullTime",
    classification: "christianOrg",
    workArrangement: "remote",
    location: "Remote",
    compensationType: "salary",
    salaryMin: 140000,
    salaryMax: 180000,
    salaryPeriod: "yearly",
    experienceLevel: "senior",
    employerId: "seed_employer_12",
    employerName: "Logos Bible Software",
    employerType: "faithFriendlyCompany",
  },
  {
    title: "Campus Pastor — New Church Plant",
    description: "Lead a new campus launch in the suburbs. Preaching, community outreach, team building. Entrepreneurial spirit and 5+ years pastoral experience needed.",
    category: "pastoralMinistry",
    jobType: "fullTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Denver, CO",
    compensationType: "salary",
    salaryMin: 60000,
    salaryMax: 80000,
    salaryPeriod: "yearly",
    experienceLevel: "senior",
    employerId: "seed_employer_13",
    employerName: "Red Rocks Church",
    employerType: "church",
  },
  {
    title: "Social Media Manager — Christian Brand",
    description: "Manage Instagram, TikTok, and YouTube for a faith-based lifestyle brand. Content creation, analytics, community engagement. 50K+ follower growth target.",
    category: "marketing",
    jobType: "fullTime",
    classification: "faithFriendly",
    workArrangement: "remote",
    location: "Remote (US)",
    compensationType: "salary",
    salaryMin: 50000,
    salaryMax: 70000,
    salaryPeriod: "yearly",
    experienceLevel: "midLevel",
    employerId: "seed_employer_14",
    employerName: "Blessed Threads Co.",
    employerType: "faithFriendlyCompany",
  },
  {
    title: "Church Bookkeeper (Part-Time)",
    description: "Manage accounts payable/receivable, payroll, and donation tracking for a 500-member church. QuickBooks experience required. 20 hrs/week.",
    category: "administration",
    jobType: "partTime",
    classification: "churchMinistry",
    workArrangement: "onSite",
    location: "Orlando, FL",
    compensationType: "hourly",
    salaryMin: 18,
    salaryMax: 25,
    salaryPeriod: "hourly",
    experienceLevel: "entryLevel",
    employerId: "seed_employer_15",
    employerName: "New Life Community Church",
    employerType: "church",
  },
];

async function seed() {
  console.log(`Seeding ${sampleJobs.length} job listings...`);

  const batch = db.batch();

  for (const job of sampleJobs) {
    const ref = db.collection("jobListings").doc();
    batch.set(ref, {
      ...job,
      isActive: true,
      isFeatured: Math.random() > 0.7, // 30% featured
      viewCount: Math.floor(Math.random() * 500),
      applicationCount: Math.floor(Math.random() * 30),
      saveCount: Math.floor(Math.random() * 50),
      safetyScore: 0.95 + Math.random() * 0.05,
      moderationState: "active",
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
  }

  await batch.commit();
  console.log(`✅ Seeded ${sampleJobs.length} job listings successfully`);
}

seed().then(() => process.exit(0)).catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
