
//
//  SmartReplySuggestionService.swift
//  AMENAPP
//
//  Generates moderated smart reply suggestions for the Reply Assist Dynamic Island.
//
//  PIPELINE (per request):
//    1. Gather minimal context (post topic + short snippet — no full post body sent off-device)
//    2. Call BereanOrchestrator with task SMART_REPLY or TONE_REWRITE
//    3. Parse JSON response: { "suggestions": ["...", "...", "..."] }
//    4. Run ThinkFirstGuardrailsService on each suggestion (blocks any that fail)
//    5. Truncate each suggestion to ≤60 chars
//    6. Return safe suggestions, or canonical fallbacks if anything fails / all blocked
//
//  SAFETY NON-NEGOTIABLES:
//    - Never display a suggestion that was not generated by this pipeline AND moderation-gated.
//    - Never send the full message body off-device; only send a ≤200 char topic excerpt.
//    - Minors protection: if sender is flagged minor, skip suggestion generation entirely.
//    - If ALL providers fail, return canonical fallback strings (never an empty array).
//

import Foundation
import FirebaseFunctions

// MARK: - Suggestion Request

struct SmartReplySuggestionRequest {
    enum SuggestionMode {
        /// Generate encouraging / thoughtful / prayerful reply chips for a comment or DM.
        case smartReply
        /// Generate a gentler rewrite of the user's draft text.
        case toneRewrite(originalDraft: String)
    }

    let mode: SuggestionMode
    /// Short topic context (≤200 chars). May be nil for DMs when privacy is restricted.
    let contextExcerpt: String?
    /// Who sent the original message (nil if privacy restricted).
    let actorDisplayName: String?
    /// Prevent suggestion generation if sender is a known minor.
    let actorIsMinor: Bool
}

// MARK: - Suggestion Result

struct SmartReplySuggestionResult {
    let suggestion1: String
    let suggestion2: String
    let suggestion3: String
    /// true = generated by AI and passed moderation. false = canonical fallbacks.
    let isAIGenerated: Bool

    static let fallback = SmartReplySuggestionResult(
        suggestion1: "I hear you.",
        suggestion2: "Thanks for sharing.",
        suggestion3: "I'm praying for you.",
        isAIGenerated: false
    )

    static let toneAssistFallback = SmartReplySuggestionResult(
        suggestion1: "I understand your concern, and I'd love to discuss this more.",
        suggestion2: "I hear you.",
        suggestion3: "Let's talk about this kindly.",
        isAIGenerated: false
    )
}

// MARK: - Service

@MainActor
final class SmartReplySuggestionService {

    static let shared = SmartReplySuggestionService()
    private init() {}

    // Cloud Function name for smart reply generation
    private let cloudFunctionName = "bereanSmartReply"

    /// Maximum character length per suggestion (enforced after generation).
    private let maxSuggestionLength = 60

    /// Maximum context excerpt to send off-device.
    private let maxContextLength = 200

    // MARK: - Public API

    /// Generate smart reply suggestions and post them to the Live Activity.
    ///
    /// Call this immediately after starting a reply activity in loading state.
    /// It runs the full pipeline and calls LiveActivityManager.updateReplySuggestions() when done.
    func generateAndUpdateActivity(
        request: SmartReplySuggestionRequest,
        contextSnippet: String?,
        activityEntityId: String
    ) {
        Task {
            let result = await generate(request: request)
            LiveActivityManager.shared.updateReplySuggestions(
                suggestion1: result.suggestion1,
                suggestion2: result.suggestion2,
                suggestion3: result.suggestion3,
                snippet: contextSnippet
            )
        }
    }

    /// Core generation pipeline. Returns fallbacks on any failure.
    func generate(request: SmartReplySuggestionRequest) async -> SmartReplySuggestionResult {
        // Safety gate: never generate suggestions involving minors
        if request.actorIsMinor {
            return .fallback
        }

        do {
            let rawSuggestions = try await callBereanOrchestrator(request: request)
            let moderated = await moderateAndFilter(suggestions: rawSuggestions)

            // If moderation blocked all suggestions, use fallbacks
            guard moderated.count >= 1 else {
                return fallbackForMode(request.mode)
            }

            let s1 = truncated(moderated[safe: 0] ?? "")
            let s2 = truncated(moderated[safe: 1] ?? "")
            let s3 = truncated(moderated[safe: 2] ?? "")

            return SmartReplySuggestionResult(
                suggestion1: s1.isEmpty ? fallbackForMode(request.mode).suggestion1 : s1,
                suggestion2: s2.isEmpty ? fallbackForMode(request.mode).suggestion2 : s2,
                suggestion3: s3.isEmpty ? fallbackForMode(request.mode).suggestion3 : s3,
                isAIGenerated: true
            )
        } catch {
            // Any network/provider failure → canonical fallbacks (never fail-open with empty)
            return fallbackForMode(request.mode)
        }
    }

    // MARK: - PII Scrubbing

    /// Replaces known PII patterns with [removed] before any text leaves the device.
    /// Patterns are sourced from BereanSafetyPolicy to keep them in one place.
    private func scrubPII(from text: String) -> String {
        var scrubbed = text
        for (pattern, _) in BereanSafetyPolicy.piiPatterns {
            if let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) {
                let range = NSRange(scrubbed.startIndex..., in: scrubbed)
                scrubbed = regex.stringByReplacingMatches(
                    in: scrubbed, options: [], range: range, withTemplate: "[removed]"
                )
            }
        }
        return scrubbed
    }

    // MARK: - Cloud Function Call

    private func callBereanOrchestrator(request: SmartReplySuggestionRequest) async throws -> [String] {
        let functions = Functions.functions()
        let fn = functions.httpsCallable(cloudFunctionName)

        // Build a minimal, privacy-safe payload
        var payload: [String: Any] = [:]

        switch request.mode {
        case .smartReply:
            payload["mode"] = "smart_reply"
            // Only send a trimmed, PII-scrubbed excerpt — never the full content
            if let excerpt = request.contextExcerpt {
                let clean = scrubPII(from: String(excerpt.prefix(maxContextLength)))
                payload["context"] = clean
            }
            // Never include actorDisplayName — not needed for suggestion quality
        case .toneRewrite(let draft):
            payload["mode"] = "tone_rewrite"
            // Send the PII-scrubbed draft so Claude can rewrite it gentler
            let clean = scrubPII(from: String(draft.prefix(500)))
            payload["draft"] = clean
        }

        let result = try await fn.call(payload)

        // Parse: { "suggestions": ["...", "...", "..."] }
        guard let data = result.data as? [String: Any],
              let suggestions = data["suggestions"] as? [String] else {
            throw SmartReplyError.invalidResponse
        }

        return suggestions
    }

    // MARK: - Moderation Gate

    /// Runs ThinkFirstGuardrailsService on each suggestion.
    /// Removes any that are blocked or require edit.
    private func moderateAndFilter(suggestions: [String]) async -> [String] {
        var safe: [String] = []
        let guardrails = ThinkFirstGuardrailsService.shared

        for text in suggestions {
            let result = guardrails.check(text: text, context: .commentReply)
            switch result.action {
            case .allow, .softPrompt:
                safe.append(text)
            case .requireEdit, .block:
                // Discard this suggestion — moderation blocked it
                break
            }
        }

        return safe
    }

    // MARK: - Helpers

    private func truncated(_ text: String) -> String {
        guard text.count > maxSuggestionLength else { return text }
        return String(text.prefix(maxSuggestionLength - 1)) + "…"
    }

    private func fallbackForMode(_ mode: SmartReplySuggestionRequest.SuggestionMode) -> SmartReplySuggestionResult {
        switch mode {
        case .smartReply:   return .fallback
        case .toneRewrite:  return .toneAssistFallback
        }
    }
}

// MARK: - Errors

private enum SmartReplyError: Error {
    case invalidResponse
    case moderationBlocked
}

// MARK: - Safe array subscript

private extension Array {
    subscript(safe index: Int) -> Element? {
        indices.contains(index) ? self[index] : nil
    }
}
