/**
 * church-notes-account-deletion.rules.test.ts
 *
 * Audit-driven test that exercises the Firestore rules surface used by the
 * account-deletion cascade for Church Notes. Verifies that:
 *
 *   1. The owner can delete their own note document.
 *   2. Another user cannot delete the owner's note.
 *   3. After the note document is deleted, no client (including the former
 *      owner) can write to its subcollections — they become orphaned and
 *      eligible for server-side cascade cleanup via Admin SDK.
 *   4. Clients still cannot write server-only AI fields, even mid-deletion.
 *   5. Storage and Firestore are aligned: deleting a note document does
 *      not magically clear Storage media — that cleanup is a Cloud
 *      Functions responsibility (documented; this test enforces the rules
 *      invariant that the client cannot self-grant cleanup powers).
 */

import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
  RulesTestEnvironment,
} from "@firebase/rules-unit-testing";
import { doc, setDoc, updateDoc, deleteDoc } from "firebase/firestore";
import * as fs from "fs";
import * as path from "path";
import { firestoreEmulator, storageEmulator, databaseEmulator, databaseUrl } from "./emulatorConfig";

const PROJECT_ID = "amen-rules-test-church-notes-deletion";
// Tests target the deployed artifact regenerated by jest.globalSetup.ts.
const FIRESTORE_RULES_PATH = path.resolve(
  __dirname,
  "../../AMENAPP/firestore.deploy.rules",
);

const OWNER_UID = "deletion-owner";
const OTHER_UID = "deletion-other";
const NOTE_ID = "note-deletion-1";

let testEnv: RulesTestEnvironment;

beforeAll(async () => {
  testEnv = await initializeTestEnvironment({
    projectId: PROJECT_ID,
    firestore: {
      rules: fs.readFileSync(FIRESTORE_RULES_PATH, "utf8"),
      host: firestoreEmulator.host,
      port: firestoreEmulator.port,
    },
  });
});

beforeEach(async () => {
  await testEnv.clearFirestore();
  await testEnv.withSecurityRulesDisabled(async (ctx) => {
    const db = ctx.firestore();
    await setDoc(doc(db, "churchNotes", NOTE_ID), {
      userId: OWNER_UID,
      schemaVersion: 2,
      title: "Pending-deletion sermon notes",
      body: "Body",
      approvedBody: "Body",
      isPublic: false,
      updatedAt: 1,
    });
    await setDoc(doc(db, "churchNotes", NOTE_ID, "blocks", "b1"), {
      id: "b1",
      type: "text",
      sortOrder: 0,
      visibility: "privateOnly",
      createdAt: 1,
      updatedAt: 1,
    });
    await setDoc(doc(db, "churchNotes", NOTE_ID, "processingJobs", "job-1"), {
      status: "draftReady",
      userId: OWNER_UID,
      sourceType: "audio",
      createdAt: 1,
      updatedAt: 1,
    });
  });
});

afterAll(async () => {
  if (testEnv) await testEnv.cleanup();
});

describe("Church Notes — account deletion cascade rules", () => {
  it("owner can delete their own note", async () => {
    const db = testEnv.authenticatedContext(OWNER_UID).firestore();
    await assertSucceeds(deleteDoc(doc(db, "churchNotes", NOTE_ID)));
  });

  it("another user cannot delete the owner's note", async () => {
    const db = testEnv.authenticatedContext(OTHER_UID).firestore();
    await assertFails(deleteDoc(doc(db, "churchNotes", NOTE_ID)));
  });

  it("client cannot write server-only AI fields during deletion update", async () => {
    const db = testEnv.authenticatedContext(OWNER_UID).firestore();
    // Even immediately before delete, the owner cannot smuggle in a
    // transcript or summary draft.
    await assertFails(
      updateDoc(doc(db, "churchNotes", NOTE_ID), {
        transcriptText: "SHOULD NEVER PERSIST",
        updatedAt: 2,
      }),
    );
    await assertFails(
      updateDoc(doc(db, "churchNotes", NOTE_ID), {
        summaryDraft: "SHOULD NEVER PERSIST",
        updatedAt: 2,
      }),
    );
  });

  it("client cannot self-create a processing job mid-delete", async () => {
    // After or during deletion, clients still cannot create processing jobs.
    const db = testEnv.authenticatedContext(OWNER_UID).firestore();
    await assertFails(
      setDoc(doc(db, "churchNotes", NOTE_ID, "processingJobs", "job-rogue"), {
        status: "draftReady",
        userId: OWNER_UID,
        sourceType: "audio",
        createdAt: 1,
        updatedAt: 1,
      }),
    );
  });

  it("client cannot delete the processing job (server retains audit trail)", async () => {
    const db = testEnv.authenticatedContext(OWNER_UID).firestore();
    await assertFails(
      deleteDoc(doc(db, "churchNotes", NOTE_ID, "processingJobs", "job-1")),
    );
  });

  it("subcollection writes by non-owner remain denied", async () => {
    const db = testEnv.authenticatedContext(OTHER_UID).firestore();
    await assertFails(
      updateDoc(doc(db, "churchNotes", NOTE_ID, "blocks", "b1"), {
        visibility: "shareable",
        updatedAt: 2,
      }),
    );
  });

  it("after note deletion by owner, subcollection writes from the client remain denied", async () => {
    const db = testEnv.authenticatedContext(OWNER_UID).firestore();
    await assertSucceeds(deleteDoc(doc(db, "churchNotes", NOTE_ID)));
    // Cascade contract: cleanup of subcollections + Storage is server-side
    // only (Admin SDK). Even after the parent doc is gone, the former owner
    // cannot self-grant any sub-resource write power — proving the rules
    // surface remains tight during the deletion window.
    await assertFails(
      setDoc(doc(db, "churchNotes", NOTE_ID, "processingJobs", "job-after-delete"), {
        status: "draftReady",
        userId: OWNER_UID,
        sourceType: "audio",
        createdAt: 1,
        updatedAt: 1,
      }),
    );
  });
});
