//
//  TrueSourceLabelChip.swift
//  AMENAPP
//
//  True Source label chip displayed on post cards and media.
//  Shows provenance, AI labels, safety labels, and review status.
//
//  Design requirements:
//  - White background, black text (no glass-on-glass)
//  - Native iOS system font (no custom fonts)
//  - Dynamic Type support
//  - VoiceOver labels
//  - Reduce Motion: no transition animations
//  - Tappable: opens TrueSourceDetailSheet
//

import SwiftUI

// MARK: - TrueSourceChipKind

enum TrueSourceChipKind: Equatable {
    case aiGenerated
    case aiAssisted(label: String)
    case editedMedia
    case unverifiedClaim
    case contextNeeded
    case sourceUnclear
    case humanReviewed
    case communityReviewed
    case sensitiveContent
    case reducedReach
    case safetyLabel(text: String)
    case provenanceLabel(status: ProvenanceStatus)

    var iconName: String {
        switch self {
        case .aiGenerated:             return "sparkles"
        case .aiAssisted:              return "sparkle"
        case .editedMedia:             return "scissors"
        case .unverifiedClaim:         return "questionmark.circle"
        case .contextNeeded:           return "info.circle"
        case .sourceUnclear:           return "link.badge.plus"
        case .humanReviewed:           return "person.badge.shield.checkmark"
        case .communityReviewed:       return "checkmark.seal"
        case .sensitiveContent:        return "eye.trianglebadge.exclamationmark"
        case .reducedReach:            return "arrow.down.right.circle"
        case .safetyLabel:             return "exclamationmark.shield"
        case .provenanceLabel(let s):
            switch s {
            case .aiGenerated:         return "sparkles"
            case .repost:              return "arrow.2.squarepath"
            case .edited:              return "pencil.circle"
            default:                   return "checkmark.circle"
            }
        }
    }

    var label: String {
        switch self {
        case .aiGenerated:             return "AI-generated media"
        case .aiAssisted(let l):       return l.isEmpty ? "AI-assisted" : l
        case .editedMedia:             return "Edited or altered media"
        case .unverifiedClaim:         return "Unverified claim"
        case .contextNeeded:           return "Context needed"
        case .sourceUnclear:           return "Source unclear"
        case .humanReviewed:           return "Human-reviewed"
        case .communityReviewed:       return "Community-reviewed"
        case .sensitiveContent:        return "Sensitive content"
        case .reducedReach:            return "Limited distribution"
        case .safetyLabel(let text):   return text
        case .provenanceLabel(let s):
            switch s {
            case .aiGenerated:         return "AI-generated"
            case .repost:              return "Repost"
            case .edited:              return "Edited"
            case .original:            return "Original"
            case .unknown:             return "Source unclear"
            }
        }
    }

    var accessibilityLabel: String {
        switch self {
        case .aiGenerated:
            return "This content was fully generated by AI"
        case .aiAssisted(let l):
            return "AI was used to assist creating this content: \(l)"
        case .editedMedia:
            return "This media has been edited or altered from its original"
        case .unverifiedClaim:
            return "This post makes a claim that has not been independently verified"
        case .contextNeeded:
            return "Additional context may help you understand this post"
        case .sourceUnclear:
            return "The original source of this content is unclear"
        case .humanReviewed:
            return "A human moderator has reviewed this content"
        case .communityReviewed:
            return "Community members have reviewed this content"
        case .sensitiveContent:
            return "This post contains sensitive content"
        case .reducedReach:
            return "This post has limited distribution due to safety concerns"
        case .safetyLabel(let text):
            return "Safety label: \(text)"
        case .provenanceLabel(let s):
            return "Content provenance: \(s.rawValue)"
        }
    }

    var chipColor: Color {
        switch self {
        case .aiGenerated, .aiAssisted:     return Color(.systemIndigo)
        case .editedMedia, .sourceUnclear:  return Color(.systemOrange)
        case .unverifiedClaim, .contextNeeded: return Color(.systemYellow)
        case .humanReviewed, .communityReviewed: return Color(.systemGreen)
        case .sensitiveContent, .reducedReach: return Color(.systemRed).opacity(0.8)
        case .safetyLabel:                  return Color(.systemRed)
        case .provenanceLabel:              return Color(.systemGray)
        }
    }
}

// MARK: - TrueSourceLabelChip

struct TrueSourceLabelChip: View {
    let kind: TrueSourceChipKind
    var onTap: (() -> Void)? = nil

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        Button {
            onTap?()
        } label: {
            HStack(spacing: 4) {
                Image(systemName: kind.iconName)
                    .imageScale(.small)
                    .accessibilityHidden(true)
                Text(kind.label)
                    .font(.caption2.weight(.medium))
                    .lineLimit(1)
            }
            .foregroundStyle(kind.chipColor)
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(
                Capsule()
                    .fill(kind.chipColor.opacity(0.1))
            )
            .overlay(
                Capsule()
                    .strokeBorder(kind.chipColor.opacity(0.3), lineWidth: 0.5)
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel(kind.accessibilityLabel)
        .accessibilityHint("Double tap to learn more about this label")
        .accessibilityAddTraits(.isButton)
        .animation(reduceMotion ? nil : .easeOut(duration: 0.15), value: kind.label)
    }
}

// MARK: - TrueSourceChipRow

/// Renders all applicable chips for a post based on its TrueSourceBundle and aiUsage.
struct TrueSourceChipRow: View {
    let post: Post
    var showDetailSheet: Bool = true

    @State private var showingDetail = false

    var chips: [TrueSourceChipKind] {
        var result: [TrueSourceChipKind] = []

        // AI-generated (highest priority — always show)
        if post.requiresAIGeneratedLabel {
            result.append(.aiGenerated)
        } else if let usage = post.aiUsage, usage.disclosureRequired {
            result.append(.aiAssisted(label: usage.primaryLabel.displayText))
        }

        // True Source bundle labels
        if let bundle = post.trueSource {
            if bundle.source.editedMedia          { result.append(.editedMedia) }
            if bundle.source.sourceUnclear        { result.append(.sourceUnclear) }
            if bundle.context.outOfContextRisk > 0.5 { result.append(.contextNeeded) }
            if bundle.context.contentType == .unverifiedClaim { result.append(.unverifiedClaim) }
            if bundle.source.humanReviewed        { result.append(.humanReviewed) }
            if bundle.source.communityReviewed    { result.append(.communityReviewed) }
            if bundle.safety.hasReducedReach      { result.append(.reducedReach) }
            for label in bundle.safety.labels.prefix(2) {
                result.append(.safetyLabel(text: label))
            }
        }

        // Legacy sensitive content
        if post.hasSensitiveContent, result.isEmpty {
            result.append(.sensitiveContent)
        }

        return Array(result.prefix(3)) // Never show more than 3 chips at once
    }

    var body: some View {
        if chips.isEmpty { EmptyView() } else {
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 6) {
                    ForEach(Array(chips.enumerated()), id: \.offset) { _, chip in
                        TrueSourceLabelChip(kind: chip) {
                            if showDetailSheet { showingDetail = true }
                        }
                    }
                }
                .padding(.horizontal, 2)
            }
            .sheet(isPresented: $showingDetail) {
                TrueSourceDetailSheet(post: post)
            }
        }
    }
}

// MARK: - TrueSourceDetailSheet

struct TrueSourceDetailSheet: View {
    let post: Post
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            List {
                // Provenance section
                Section("Content Origin") {
                    if let bundle = post.trueSource {
                        LabeledContent("Provenance", value: bundle.source.provenanceStatus.rawValue.replacingOccurrences(of: "_", with: " ").capitalized)
                        LabeledContent("Integrity score", value: String(format: "%.0f%%", bundle.source.sourceIntegrityScore * 100))
                        if bundle.source.aiGenerated {
                            HStack {
                                Image(systemName: "sparkles")
                                    .foregroundStyle(.indigo)
                                    .accessibilityHidden(true)
                                Text("This content was generated by AI")
                                    .font(.subheadline)
                            }
                        }
                        if bundle.source.aiAssisted {
                            HStack {
                                Image(systemName: "sparkle")
                                    .foregroundStyle(.indigo)
                                    .accessibilityHidden(true)
                                Text("AI tools assisted the author with this content")
                                    .font(.subheadline)
                            }
                        }
                        if bundle.source.editedMedia {
                            HStack {
                                Image(systemName: "scissors")
                                    .foregroundStyle(.orange)
                                    .accessibilityHidden(true)
                                Text("The media in this post has been edited from its original")
                                    .font(.subheadline)
                            }
                        }
                        if bundle.source.humanReviewed {
                            HStack {
                                Image(systemName: "checkmark.shield.fill")
                                    .foregroundStyle(.green)
                                    .accessibilityHidden(true)
                                Text("A human moderator has reviewed this post")
                                    .font(.subheadline)
                            }
                        }
                    } else {
                        Text("Source information is being verified.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                }

                // AI usage section
                if let usage = post.aiUsage, (usage.usedAI || usage.disclosureRequired) {
                    Section("AI Assistance") {
                        Text(usage.primaryLabel.displayText)
                            .font(.subheadline)
                        Text("The author stayed in control of the final post.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                // Safety labels section
                if let bundle = post.trueSource, !bundle.safety.labels.isEmpty {
                    Section("Safety Labels") {
                        ForEach(bundle.safety.labels, id: \.self) { label in
                            Label(label, systemImage: "exclamationmark.shield")
                                .font(.subheadline)
                                .accessibilityLabel("Safety label: \(label)")
                        }
                    }
                }

                Section {
                    Text("Amen uses automated systems and human reviewers to help you understand what you're seeing. Labels are based on our Community Guidelines.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
            .navigationTitle("About This Post")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                        .accessibilityLabel("Close About This Post sheet")
                }
            }
        }
        .presentationDetents([.medium, .large])
    }
}

// MARK: - WhyAmISeeingThisSheet

struct WhyAmISeeingThisSheet: View {
    let post: Post
    var reason: WhyAmISeeingThisReason
    @Environment(\.dismiss) private var dismiss

    enum WhyAmISeeingThisReason {
        case followedCreator(creatorName: String)
        case similarInterest(topic: String)
        case trendingTopic(topic: String)
        case communityRelevance
        case savedTopicRecommendation(topic: String)
        case friendActivity
        case unknown

        var headline: String {
            switch self {
            case .followedCreator(let name): return "You follow \(name)"
            case .similarInterest(let topic): return "Based on your interest in \(topic)"
            case .trendingTopic(let topic): return "\(topic) is trending in your community"
            case .communityRelevance: return "Relevant to your community"
            case .savedTopicRecommendation(let topic): return "You saved posts about \(topic)"
            case .friendActivity: return "People you follow engaged with this"
            case .unknown: return "Recommended for you"
            }
        }

        var detail: String {
            switch self {
            case .followedCreator: return "This post is from someone you follow."
            case .similarInterest(let topic):
                return "You've engaged with content about \(topic) recently. We show similar posts."
            case .trendingTopic(let topic):
                return "\(topic) is being discussed widely in your faith community right now."
            case .communityRelevance:
                return "This was posted in a community or group you're part of."
            case .savedTopicRecommendation(let topic):
                return "You've saved or bookmarked content about \(topic). We show related posts."
            case .friendActivity:
                return "People you're connected with have engaged with this content."
            case .unknown:
                return "This post was recommended based on your activity. You can tune your feed below."
            }
        }

        var notBecauseOf: String {
            "Not because of any sensitive personal attributes, demographics, political views, or purchase history."
        }
    }

    var body: some View {
        NavigationStack {
            List {
                Section {
                    VStack(alignment: .leading, spacing: 8) {
                        Text(reason.headline)
                            .font(.headline)
                        Text(reason.detail)
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                    .padding(.vertical, 4)
                }

                Section {
                    Text(reason.notBecauseOf)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Section("Manage This") {
                    NavigationLink("Tune your feed") {
                        // Links to HeyFeedControlsSheet equivalent
                        Text("Feed tuning coming here")
                    }
                    .accessibilityLabel("Tune your feed to see more or less of this type of content")

                    NavigationLink("About True Source labels") {
                        TrueSourceDetailSheet(post: post)
                    }
                    .accessibilityLabel("Learn about the True Source content labels on this post")
                }
            }
            .navigationTitle("Why Am I Seeing This?")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                        .accessibilityLabel("Close Why Am I Seeing This sheet")
                }
            }
        }
        .presentationDetents([.medium])
    }
}

// MARK: - Previews

#if DEBUG
#Preview("TrueSourceLabelChip") {
    VStack(alignment: .leading, spacing: 12) {
        TrueSourceLabelChip(kind: .aiGenerated)
        TrueSourceLabelChip(kind: .aiAssisted(label: "Tone checked"))
        TrueSourceLabelChip(kind: .editedMedia)
        TrueSourceLabelChip(kind: .unverifiedClaim)
        TrueSourceLabelChip(kind: .contextNeeded)
        TrueSourceLabelChip(kind: .humanReviewed)
        TrueSourceLabelChip(kind: .reducedReach)
    }
    .padding()
}
#endif
