// AmenCreateSpaceViewModel.swift — AMEN App / Spiritual OS
// Agent E: Enhanced Create Space flow — ViewModel layer.
// Writes to Firestore `spaces` collection with extended fields.

import Foundation
import FirebaseFirestore

// MARK: - Supporting Types

/// Pastoral roles assignable to a Space member.
enum SpacePastoralRole: String, CaseIterable {
    case leader
    case member
    case moderator
    case pastor

    var displayLabel: String {
        switch self {
        case .leader:    return "Leader"
        case .member:    return "Member"
        case .moderator: return "Moderator"
        case .pastor:    return "Pastor"
        }
    }
}

/// A draft member record before the Space is persisted.
struct SpaceMemberDraft: Identifiable {
    let id: String
    var displayName: String
    var avatarURL: URL?
    var role: SpacePastoralRole
}

/// Feature toggle flags surfaced in the create flow.
struct SpaceFeatureToggles {
    var churchNotes: Bool   = true
    var bereanEnabled: Bool = false
    var events: Bool        = true
    var resources: Bool     = true
    var prayerWall: Bool    = true

    /// Serialised as a plain [String: Bool] map for Firestore.
    var firestoreMap: [String: Bool] {
        [
            "churchNotes":    churchNotes,
            "bereanEnabled":  bereanEnabled,
            "events":         events,
            "resources":      resources,
            "prayerWall":     prayerWall,
        ]
    }
}

// MARK: - ViewModel

@MainActor
final class AmenCreateSpaceViewModel: ObservableObject {

    // MARK: - Form Fields

    @Published var spaceName: String = ""
    @Published var spaceDescription: String = ""
    @Published var coverImageURL: URL? = nil
    @Published var isPrivate: Bool = false
    @Published var encryptedPrayerWall: Bool = false
    @Published var addBereanAsMember: Bool = false
    @Published var features: SpaceFeatureToggles = SpaceFeatureToggles()
    @Published var members: [SpaceMemberDraft] = []

    // MARK: - Submission State

    @Published var isSubmitting: Bool = false
    @Published var submitError: String? = nil
    @Published var isSubmitted: Bool = false

    // MARK: - Validation

    var isValid: Bool {
        !spaceName.trimmingCharacters(in: .whitespaces).isEmpty
    }

    // MARK: - Member Management

    func addMember(_ member: SpaceMemberDraft) {
        members.append(member)
    }

    func removeMember(id: String) {
        members.removeAll { $0.id == id }
    }

    func updateRole(memberId: String, role: SpacePastoralRole) {
        guard let index = members.firstIndex(where: { $0.id == memberId }) else { return }
        members[index].role = role
    }

    // MARK: - Submission

    func submit(creatorUserId: String) async {
        guard isValid else { return }

        isSubmitting = true
        submitError = nil

        let db = Firestore.firestore()
        let ref = db.collection("spaces").document()

        let payload: [String: Any] = [
            "name":                spaceName.trimmingCharacters(in: .whitespaces),
            "description":         spaceDescription.trimmingCharacters(in: .whitespaces),
            "isPrivate":           isPrivate,
            "creatorUid":          creatorUserId,
            "encryptedPrayerWall": encryptedPrayerWall,
            "addBereanAsMember":   addBereanAsMember,
            "heroCardEnabled":     false,
            "featureToggles":      features.firestoreMap,
            "memberCount":         1,
            "postCount":           0,
            "weeklyActiveUsers":   1,
            "isAutoGenerated":     false,
            "topPostIds":          [String](),
            "recentPosterPhotoURLs": [String](),
            "createdAt":           FieldValue.serverTimestamp(),
        ]

        do {
            try await ref.setData(payload)

            // Auto-enroll creator as leader
            let membershipId = "\(creatorUserId)_\(ref.documentID)"
            try? await db.collection("spaceMemberships")
                .document(membershipId)
                .setData([
                    "userId":                 creatorUserId,
                    "spaceId":                ref.documentID,
                    "role":                   SpacePastoralRole.leader.rawValue,
                    "joinedAt":               FieldValue.serverTimestamp(),
                    "notificationsEnabled":   true,
                ])

            isSubmitting = false
            isSubmitted = true
        } catch {
            isSubmitting = false
            submitError = error.localizedDescription
        }
    }
}
