//
//  AIContentDetectionService.swift
//  AMENAPP
//
//  Created by Claude on 2/23/26.
//

import Foundation
import FirebaseFirestore
import FirebaseAuth

/// Service to detect AI-generated content in posts
class AIContentDetectionService {
    static let shared = AIContentDetectionService()
    
    private init() {}
    
    // MARK: - AI Detection Patterns
    
    /// Common AI-generated content patterns and phrases
    private let aiPatterns = [
        // ChatGPT/Claude/AI identifiers
        "as an ai", "as a language model", "i'm an ai", "i am an ai",
        "i don't have personal", "i cannot provide personal",
        "i'm unable to", "i cannot recommend", "i apologize, but",
        "as an artificial", "i'm a large language model",
        
        // Generic AI phrases
        "certainly!", "absolutely!", "here's a breakdown",
        "in summary:", "to summarize:", "key takeaways:",
        "it's important to note", "it's worth noting",
        "it's crucial to", "it's essential to",
        "here are some", "here's what you need to know",
        "let me explain", "let's break this down",
        "to put it simply", "in other words",
        "the key point is", "the main takeaway",
        
        // Overly enthusiastic AI language
        "i'd be happy to", "i'd be glad to",
        "great question!", "excellent question!",
        "happy to help", "glad you asked",
        
        // Formal transitions
        "furthermore", "moreover", "additionally",
        "consequently", "therefore", "thus",
        "in conclusion", "to conclude",
        "that being said", "with that in mind"
    ]
    
    /// AI-generated spiritual content patterns
    private let aiSpiritualPatterns = [
        "as a christian ai", "biblical perspective suggests",
        "theological framework indicates", "scholars agree that",
        "from a theological standpoint", "in christian theology",
        "the scriptures teach us that", "god's word reminds us",
        "scripture tells us", "the bible teaches",
        "many theologians believe", "church tradition holds",
        "from a biblical perspective", "scriptural evidence suggests"
    ]
    
    /// AI-generated inspirational/quote patterns
    private let aiInspirationalPatterns = [
        "is often built", "remember that", "don't forget that",
        "it's not about", "true strength", "real growth",
        "genuine peace", "authentic joy", "keep choosing",
        "keep remembering", "never forget", "always remember"
    ]
    
    /// AI source identifiers and artifacts (ChatGPT, Claude, etc.)
    private let aiSourceArtifacts = [
        // ChatGPT artifacts
        "chatgpt", "chat gpt", "gpt-4", "gpt-3", "openai",
        "generated by chatgpt", "from chatgpt",
        
        // Claude artifacts  
        "claude", "anthropic", "generated by claude", "from claude",
        
        // Generic AI tools
        "generated by ai", "ai generated", "created with ai",
        "gemini", "bard", "copilot",
        
        // Copy/paste artifacts (invisible characters, formatting)
        "​", "‌", "‍" // Zero-width spaces that AI chat interfaces sometimes add
    ]
    
    // MARK: - Detection Methods
    
    /// Detect if content is likely AI-generated
    /// - Parameters:
    ///   - text: The content to analyze
    ///   - pastedRatio: Optional ratio of pasted vs typed content (0.0-1.0)
    func detectAIContent(_ text: String, pastedRatio: Double? = nil) async -> AIContentDetectionResult {
        dlog("🔍 AI Detection analyzing content (length: \(text.count))")
        if let ratio = pastedRatio {
            dlog("   📋 Paste ratio: \(Int(ratio * 100))%")
        }
        
        let lowercased = text.lowercased()
        var score: Double = 0.0
        var matchedPatterns: [String] = []
        
        // Check for AI patterns (0.4 per match to make it more sensitive)
        for pattern in aiPatterns {
            if lowercased.contains(pattern) {
                score += 0.4
                matchedPatterns.append(pattern)
                dlog("   ✓ Matched pattern: '\(pattern)' (+0.4)")
            }
        }
        
        // Check for AI spiritual patterns (higher weight - 0.6)
        for pattern in aiSpiritualPatterns {
            if lowercased.contains(pattern) {
                score += 0.6
                matchedPatterns.append(pattern)
                dlog("   ✓ Matched spiritual pattern: '\(pattern)' (+0.6)")
            }
        }
        
        // Check for AI inspirational patterns (medium weight - 0.3)
        for pattern in aiInspirationalPatterns {
            if lowercased.contains(pattern) {
                score += 0.3
                matchedPatterns.append(pattern)
                dlog("   ✓ Matched inspirational pattern: '\(pattern)' (+0.3)")
            }
        }
        
        // Check for AI source artifacts (INSTANT BLOCK - 1.0 weight)
        for artifact in aiSourceArtifacts {
            if lowercased.contains(artifact) || text.contains(artifact) {
                score += 1.0 // Instant block
                matchedPatterns.append("AI source: \(artifact)")
                dlog("   🚨 DETECTED AI SOURCE: '\(artifact)' (+1.0 - INSTANT BLOCK)")
            }
        }
        
        // Check for excessive structure (numbered lists, bullet points)
        let structureScore = detectExcessiveStructure(text)
        if structureScore > 0 {
            dlog("   ✓ Structure detected: +\(structureScore)")
            score += structureScore
            matchedPatterns.append("structured format")
        }
        
        // Check for overly formal language
        let formalityScore = detectFormalLanguage(text)
        if formalityScore > 0 {
            dlog("   ✓ Formal language detected: +\(formalityScore)")
            score += formalityScore
            matchedPatterns.append("formal language")
        }
        
        // Check for repetitive phrases (AI hallmark)
        let repetitionScore = detectRepetitivePatterns(text)
        if repetitionScore > 0 {
            dlog("   ✓ Repetitive patterns detected: +\(repetitionScore)")
            score += repetitionScore
            matchedPatterns.append("repetitive patterns")
        }
        
        // Check for markdown formatting (AI often uses markdown)
        let markdownScore = detectMarkdownFormatting(text)
        if markdownScore > 0 {
            dlog("   ✓ Markdown formatting detected: +\(markdownScore)")
            score += markdownScore
            matchedPatterns.append("markdown formatting")
        }
        
        // Check for overly long, perfectly structured paragraphs
        let structuredParagraphScore = detectPerfectParagraphs(text)
        if structuredParagraphScore > 0 {
            dlog("   ✓ Perfect paragraphs detected: +\(structuredParagraphScore)")
            score += structuredParagraphScore
            matchedPatterns.append("overly structured")
        }
        
        // Check paste ratio - if content is 100% pasted and > 50 chars, add suspicion
        if let ratio = pastedRatio {
            if ratio >= 0.95 && text.count > 100 {
                // Very high paste ratio with substantial content = likely AI
                let pasteScore = 0.35
                dlog("   ✓ Very high paste ratio (\(Int(ratio * 100))%) with \(text.count) chars: +\(pasteScore)")
                score += pasteScore
                matchedPatterns.append("95%+ pasted content")
            } else if ratio >= 0.9 && text.count > 50 {
                let pasteScore = 0.25
                dlog("   ✓ High paste ratio detected (\(Int(ratio * 100))%): +\(pasteScore)")
                score += pasteScore
                matchedPatterns.append("90%+ pasted content")
            }
            
            // Single large paste (no typing at all) is highly suspicious
            if ratio == 1.0 && text.count > 80 {
                let singlePasteScore = 0.2
                dlog("   ✓ Single large paste (no typing): +\(singlePasteScore)")
                score += singlePasteScore
                matchedPatterns.append("single paste, no edits")
            }
        }
        
        // Detect inspirational quote style (short, impactful, generic wisdom)
        let quoteScore = detectInspirationQuoteStyle(text)
        if quoteScore > 0 {
            dlog("   ✓ Inspirational quote style detected: +\(quoteScore)")
            score += quoteScore
            matchedPatterns.append("generic wisdom style")
        }
        
        // Detect unusual Unicode/formatting from AI chat interfaces
        let unicodeScore = detectAIUnicodeArtifacts(text)
        if unicodeScore > 0 {
            dlog("   ✓ AI Unicode artifacts detected: +\(unicodeScore)")
            score += unicodeScore
            matchedPatterns.append("AI formatting artifacts")
        }
        
        // Normalize score to 0-1
        let confidence = min(score, 1.0)
        
        dlog("📊 Total confidence score: \(String(format: "%.2f", confidence)) (\(Int(confidence * 100))%)")
        dlog("   Threshold: 0.4 (40%)")
        dlog("   Result: \(confidence >= 0.4 ? "🚫 BLOCKED" : "✅ ALLOWED")")
        
        let isAIGenerated = confidence >= 0.4 // Lowered threshold to 40% to be more aggressive
        
        return AIContentDetectionResult(
            isAIGenerated: isAIGenerated,
            confidence: confidence,
            matchedPatterns: matchedPatterns,
            reason: generateReason(confidence: confidence, patterns: matchedPatterns)
        )
    }
    
    /// Detect excessive structure (numbered lists, bullet points)
    private func detectExcessiveStructure(_ text: String) -> Double {
        let numberedListPattern = #"\n\d+\."#
        let bulletPattern = #"\n[•\-\*]"#
        
        let numberedMatches = text.range(of: numberedListPattern, options: .regularExpression) != nil
        let bulletMatches = text.range(of: bulletPattern, options: .regularExpression) != nil
        
        var score: Double = 0.0
        if numberedMatches { score += 0.2 }
        if bulletMatches { score += 0.1 }
        
        return score
    }
    
    /// Detect overly formal language
    private func detectFormalLanguage(_ text: String) -> Double {
        let formalWords = ["furthermore", "moreover", "nevertheless", "consequently", "therefore", "thus", "hence"]
        let lowercased = text.lowercased()
        
        var count = 0
        for word in formalWords {
            if lowercased.contains(word) {
                count += 1
            }
        }
        
        // More than 2 formal words = likely AI
        return count >= 2 ? 0.2 : 0.0
    }
    
    /// Detect repetitive patterns
    private func detectRepetitivePatterns(_ text: String) -> Double {
        // Split into sentences
        let sentences = text.components(separatedBy: CharacterSet(charactersIn: ".!?"))
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        
        guard sentences.count > 3 else { return 0.0 }
        
        // Check if sentences start with similar words
        let starters = sentences.prefix(5).map { sentence in
            sentence.components(separatedBy: " ").first?.lowercased() ?? ""
        }
        
        let uniqueStarters = Set(starters)
        
        // If most sentences start the same way, it's likely AI
        if Double(uniqueStarters.count) / Double(starters.count) < 0.6 {
            return 0.2
        }
        
        return 0.0
    }
    
    /// Detect markdown formatting (**, ##, -, etc.)
    private func detectMarkdownFormatting(_ text: String) -> Double {
        var score: Double = 0.0
        
        // Check for markdown headers (##, ###)
        if text.contains("##") || text.contains("###") {
            score += 0.3
        }
        
        // Check for markdown bold (**text**)
        if text.contains("**") {
            score += 0.2
        }
        
        // Check for markdown lists (- item, * item)
        let lines = text.components(separatedBy: .newlines)
        let markdownListLines = lines.filter { 
            $0.trimmingCharacters(in: .whitespaces).hasPrefix("- ") || 
            $0.trimmingCharacters(in: .whitespaces).hasPrefix("* ")
        }
        if markdownListLines.count >= 2 {
            score += 0.3
        }
        
        return score
    }
    
    /// Detect perfectly structured paragraphs (AI signature)
    private func detectPerfectParagraphs(_ text: String) -> Double {
        let paragraphs = text.components(separatedBy: "\n\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        
        guard paragraphs.count >= 3 else { return 0.0 }
        
        // Check if all paragraphs are similar length (AI tends to do this)
        let lengths = paragraphs.map { $0.count }
        let avgLength = Double(lengths.reduce(0, +)) / Double(lengths.count)
        
        // Check variance - AI has low variance
        let variance = lengths.map { pow(Double($0) - avgLength, 2) }.reduce(0, +) / Double(lengths.count)
        let stdDev = sqrt(variance)
        
        // If standard deviation is less than 20% of average, it's suspiciously uniform
        if stdDev < (avgLength * 0.2) && paragraphs.count >= 3 {
            return 0.25
        }
        
        return 0.0
    }
    
    /// Detect inspirational quote style (generic wisdom, impactful phrasing)
    private func detectInspirationQuoteStyle(_ text: String) -> Double {
        var score: Double = 0.0
        let lowercased = text.lowercased()
        
        // Check for passive/abstract subject patterns
        let genericSubjects = ["life", "peace", "strength", "growth", "joy", "love", "faith"]
        let subjectCount = genericSubjects.filter { lowercased.contains($0) }.count
        if subjectCount >= 2 {
            score += 0.15
        }
        
        // Check for vague action verbs common in AI wisdom
        let vagueActions = ["is built", "is found", "comes from", "lies in", "begins with", "starts with"]
        if vagueActions.contains(where: { lowercased.contains($0) }) {
            score += 0.15
        }
        
        // Check for universal statements ("nobody sees", "everyone knows")
        let universalPatterns = ["nobody", "everyone", "people", "we all", "you'll find"]
        if universalPatterns.contains(where: { lowercased.contains($0) }) {
            score += 0.1
        }
        
        // Check for "not X, but Y" structure (common in AI wisdom)
        if lowercased.contains("not") && (lowercased.contains("but") || lowercased.contains("just")) {
            score += 0.15
        }
        
        // Short, impactful sentence (80-200 chars) with no personal pronouns
        let hasPersonalPronoun = lowercased.contains("i ") || lowercased.contains("my ") || 
                                  lowercased.contains("i'm") || lowercased.contains("me ")
        if text.count >= 80 && text.count <= 250 && !hasPersonalPronoun {
            score += 0.15
        }
        
        return score
    }
    
    /// Detect Unicode artifacts and formatting from AI chat interfaces
    private func detectAIUnicodeArtifacts(_ text: String) -> Double {
        var score: Double = 0.0
        
        // Zero-width characters (often added by web-based AI chat interfaces)
        let zeroWidthChars: [Character] = ["\u{200B}", "\u{200C}", "\u{200D}", "\u{FEFF}"]
        for char in zeroWidthChars {
            if text.contains(char) {
                score += 0.5 // Strong indicator
                break
            }
        }
        
        // Smart quotes (curly quotes) - ChatGPT often uses these
        let smartQuoteChars = ["\u{201C}", "\u{201D}", "\u{2018}", "\u{2019}"] // ""''
        var smartQuoteCount = 0
        for charStr in smartQuoteChars {
            smartQuoteCount += text.components(separatedBy: charStr).count - 1
        }
        if smartQuoteCount >= 2 {
            score += 0.2
        }
        
        // Em dashes and en dashes (—, –) - more common in AI writing
        if text.contains("—") || text.contains("–") {
            score += 0.15
        }
        
        // Multiple consecutive spaces or unusual spacing (copy/paste artifacts)
        if text.contains("  ") { // Double space
            let doubleSpaceCount = text.components(separatedBy: "  ").count - 1
            if doubleSpaceCount >= 2 {
                score += 0.1
            }
        }
        
        return score
    }
    
    /// Generate human-readable reason
    private func generateReason(confidence: Double, patterns: [String]) -> String {
        if confidence < 0.2 {
            return "Content appears genuine"
        } else if confidence < 0.4 {
            return "Content may be AI-assisted"
        } else if confidence < 0.6 {
            return "Content likely AI-generated. Detected: \(patterns.prefix(3).joined(separator: ", "))"
        } else if confidence < 0.8 {
            return "High confidence AI content. Detected: \(patterns.prefix(3).joined(separator: ", "))"
        } else {
            return "Very high confidence AI content. Multiple AI patterns detected."
        }
    }
    
    // MARK: - Post Handling
    
    /// Check post content and take action if AI-generated
    func checkAndHandlePost(postId: String, content: String, userId: String) async throws -> AIContentAction {
        let result = await detectAIContent(content)
        
        guard result.isAIGenerated else {
            return .allowed
        }
        
        // Log the detection
        dlog("🤖 AI content detected in post \(postId)")
        dlog("   Confidence: \(String(format: "%.1f%%", result.confidence * 100))")
        dlog("   Reason: \(result.reason)")
        
        // Flag the post in Firestore
        try await flagPost(postId: postId, result: result)
        
        // Notify the user
        try await notifyUser(userId: userId, result: result)
        
        // Return action based on confidence
        if result.confidence >= 0.7 {
            // Auto-delete high confidence AI content
            try await deletePost(postId: postId)
            return .deleted
        } else {
            // Flag for review
            return .flagged
        }
    }
    
    /// Flag post as AI-generated
    private func flagPost(postId: String, result: AIContentDetectionResult) async throws {
        let db = Firestore.firestore()
        
        try await db.collection("posts").document(postId).updateData([
            "aiDetection": [
                "flagged": true,
                "confidence": result.confidence,
                "reason": result.reason,
                "detectedAt": FieldValue.serverTimestamp(),
                "patterns": result.matchedPatterns
            ]
        ])
    }
    
    /// Delete post
    private func deletePost(postId: String) async throws {
        let db = Firestore.firestore()
        
        // Soft delete (mark as deleted)
        try await db.collection("posts").document(postId).updateData([
            "deleted": true,
            "deletedAt": FieldValue.serverTimestamp(),
            "deletionReason": "AI-generated content detected"
        ])
    }
    
    /// Notify user about AI detection
    private func notifyUser(userId: String, result: AIContentDetectionResult) async throws {
        let db = Firestore.firestore()
        
        let notificationData: [String: Any] = [
            "userId": userId,
            "type": "ai_content_warning",
            "title": "Share Your Own Voice",
            "message": result.confidence >= 0.7
                ? "Your post was removed because it appears to be AI-generated. AMEN is a community for authentic, personal sharing. We want to hear from you, not from AI tools."
                : "Your post has been flagged for review. AMEN is a community for authentic, personal sharing. Please share your personal thoughts, experiences, and reflections.",
            "createdAt": FieldValue.serverTimestamp(),
            "read": false,
            "severity": result.confidence >= 0.7 ? "high" : "medium"
        ]
        
        try await db.collection("users").document(userId)
            .collection("notifications").addDocument(data: notificationData)
    }
    
    // MARK: - Batch Detection for Existing Posts
    
    /// Scan existing posts for AI content
    func scanExistingPosts(batchSize: Int = 50) async throws -> ScanResult {
        let db = Firestore.firestore()
        
        var totalScanned = 0
        var flaggedCount = 0
        var deletedCount = 0
        
        // Get posts that haven't been scanned yet
        let snapshot = try await db.collection("posts")
            .whereField("aiDetection.flagged", isEqualTo: false)
            .limit(to: batchSize)
            .getDocuments()
        
        for document in snapshot.documents {
            guard let content = document.data()["content"] as? String,
                  let userId = document.data()["userId"] as? String else {
                continue
            }
            
            totalScanned += 1
            
            let action = try await checkAndHandlePost(
                postId: document.documentID,
                content: content,
                userId: userId
            )
            
            switch action {
            case .flagged:
                flaggedCount += 1
            case .deleted:
                deletedCount += 1
            case .allowed:
                break
            }
        }
        
        return ScanResult(
            totalScanned: totalScanned,
            flaggedCount: flaggedCount,
            deletedCount: deletedCount
        )
    }
}

// MARK: - Models

struct AIContentDetectionResult {
    let isAIGenerated: Bool
    let confidence: Double // 0.0 to 1.0
    let matchedPatterns: [String]
    let reason: String
}

enum AIContentAction {
    case allowed
    case flagged
    case deleted
}

struct ScanResult {
    let totalScanned: Int
    let flaggedCount: Int
    let deletedCount: Int
}
