// Space.swift — AMEN App
// Models for Spaces (Community Rooms), SpacePosts, and SpaceMemberships

import Foundation
import FirebaseFirestore

// MARK: - Space

struct AMENSpace: Identifiable, Codable {
    @DocumentID var id: String?
    var name: String
    var description: String
    var aiDetectedTopics: [String]
    var memberCount: Int
    var postCount: Int
    var coverImageURL: String?
    var createdAt: Date?
    var isAutoGenerated: Bool
    var topPostIds: [String]
    var weeklyActiveUsers: Int
    var recentPosterPhotoURLs: [String]   // last 3 posters for avatar stack

    enum CodingKeys: String, CodingKey {
        case id, name, description, aiDetectedTopics, memberCount, postCount,
             coverImageURL, createdAt, isAutoGenerated, topPostIds,
             weeklyActiveUsers, recentPosterPhotoURLs
    }

    static let placeholder = AMENSpace(
        name: "Prayer & Intercession",
        description: "A community united in prayer for one another.",
        aiDetectedTopics: ["prayer", "intercession", "faith"],
        memberCount: 842,
        postCount: 1204,
        coverImageURL: nil,
        createdAt: Date(),
        isAutoGenerated: false,
        topPostIds: [],
        weeklyActiveUsers: 234,
        recentPosterPhotoURLs: []
    )
}

// MARK: - SpacePost

struct SpacePost: Identifiable, Codable {
    @DocumentID var id: String?
    var spaceId: String
    var authorId: String
    var authorName: String?
    var authorPhotoURL: String?
    var contentType: ContentType
    var textContent: String?
    var mediaURLs: [String]
    var aiConfidenceScore: Double
    var likes: Int
    var comments: Int
    var createdAt: Date?

    enum ContentType: String, Codable {
        case text, photo, video
    }

    enum CodingKeys: String, CodingKey {
        case id, spaceId, authorId, authorName, authorPhotoURL, contentType,
             textContent, mediaURLs, aiConfidenceScore, likes, comments, createdAt
    }
}

// MARK: - SpaceMembership

struct SpaceMembership: Identifiable, Codable {
    @DocumentID var id: String?
    var userId: String
    var spaceId: String
    var joinedAt: Date?
    var notificationsEnabled: Bool
    var role: String    // always "member"

    enum CodingKeys: String, CodingKey {
        case id, userId, spaceId, joinedAt, notificationsEnabled, role
    }
}
