// SteelManCardView.swift — AMEN App
// Collapsible glass card for AI-generated steel-man arguments.

import SwiftUI

struct SteelManCardView: View {
    let label: String
    let text: String
    let tintColor: Color
    @Binding var isExpanded: Bool

    // Convenience init for callers that want local state
    init(label: String, text: String, tintColor: Color, isExpanded: Binding<Bool>) {
        self.label = label
        self.text = text
        self.tintColor = tintColor
        self._isExpanded = isExpanded
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header row — tappable
            Button {
                withAnimation(Motion.adaptive(.spring(response: 0.4, dampingFraction: 0.75))) {
                    isExpanded.toggle()
                }
            } label: {
                HStack(spacing: 10) {
                    // AI badge
                    HStack(spacing: 4) {
                        Image(systemName: "sparkles")
                            .font(.systemScaled(10, weight: .bold))
                        Text("AI")
                            .font(.systemScaled(10, weight: .bold))
                    }
                    .foregroundColor(tintColor)
                    .padding(.horizontal, 7)
                    .padding(.vertical, 3)
                    .background(
                        Capsule()
                            .fill(tintColor.opacity(0.15))
                            .overlay(Capsule().strokeBorder(tintColor.opacity(0.3), lineWidth: 1))
                    )

                    Text(label)
                        .font(.systemScaled(14, weight: .semibold))
                        .foregroundColor(.black.opacity(0.9))

                    Spacer()

                    Image(systemName: "chevron.down")
                        .font(.systemScaled(12, weight: .semibold))
                        .foregroundColor(.black.opacity(0.5))
                        .rotationEffect(.degrees(isExpanded ? 180 : 0))
                        .animation(.spring(response: 0.4, dampingFraction: 0.75), value: isExpanded)
                }
                .padding(.horizontal, 14)
                .padding(.top, 12)
                .padding(.bottom, isExpanded ? 6 : 12)
            }
            .buttonStyle(.plain)

            // Disclaimer
            Text("Generated by AI to help you understand the opposing view")
                .font(.systemScaled(11))
                .foregroundColor(.black.opacity(0.45))
                .padding(.horizontal, 14)
                .padding(.bottom, isExpanded ? 8 : 12)

            // Expandable content
            if isExpanded {
                Divider()
                    .background(tintColor.opacity(0.2))
                    .padding(.horizontal, 14)

                Text(text.isEmpty ? "No steel-man available for this post." : text)
                    .font(.systemScaled(15))
                    .italic()
                    .foregroundColor(.black.opacity(0.78))
                    .lineSpacing(4)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 12)
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(.ultraThinMaterial)
                .overlay(
                    RoundedRectangle(cornerRadius: 14, style: .continuous)
                        .fill(
                            LinearGradient(
                                stops: [
                                    .init(color: Color.white.opacity(0.90), location: 0.0),
                                    .init(color: Color.white.opacity(0.72), location: 1.0)
                                ],
                                startPoint: .top,
                                endPoint: .bottom
                            )
                        )
                )
                .overlay(
                    RoundedRectangle(cornerRadius: 14, style: .continuous)
                        .strokeBorder(Color.black.opacity(0.06), lineWidth: 0.8)
                )
        )
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
    }
}
