/**
 * BehavioralAlertConsumerService.ts
 *
 * Processes behavioralAlerts generated by BehavioralPatternService.
 * Critical and high severity alerts are routed to the human review queue
 * and push-notified to on-call safety reviewers via FCM admin topics.
 */

import { onDocumentCreated } from "firebase-functions/v2/firestore";
import * as logger from "firebase-functions/logger";
import * as admin from "firebase-admin";

if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();

interface BehavioralAlert {
  alertType: string;
  severity: "critical" | "high" | "moderate" | "low";
  senderUid?: string;
  targetUid?: string;
  metadata?: Record<string, unknown>;
  createdAt: admin.firestore.Timestamp;
}

/**
 * onBehavioralAlertCreated
 *
 * Triggers whenever BehavioralPatternService writes a new alert doc.
 * Routes the alert based on severity:
 *   critical → immediate human review queue item + FCM to safety-oncall topic
 *   high     → human review queue item
 *   moderate → logged only (batch review)
 *   low      → no action (informational)
 */
export const onBehavioralAlertCreated = onDocumentCreated(
  "behavioralAlerts/{alertId}",
  async (event) => {
    const snap = event.data;
    if (!snap) return;

    const alert = snap.data() as BehavioralAlert;
    const alertId = event.params.alertId;

    logger.info(
      `[BehavioralAlertConsumer] Processing alert ${alertId} — type=${alert.alertType} severity=${alert.severity}`
    );

    if (alert.severity === "critical" || alert.severity === "high") {
      await routeToHumanReviewQueue(alertId, alert);
    }

    if (alert.severity === "critical") {
      await notifySafetyOncall(alertId, alert);
    }
  }
);

async function routeToHumanReviewQueue(
  alertId: string,
  alert: BehavioralAlert
): Promise<void> {
  try {
    await db.collection("humanReviewQueue").add({
      sourceType: "behavioral_alert",
      sourceId: alertId,
      alertType: alert.alertType,
      severity: alert.severity,
      senderUid: alert.senderUid ?? null,
      targetUid: alert.targetUid ?? null,
      status: "pending",
      priority: alert.severity === "critical" ? 1 : 2,
      assignedTo: null,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      metadata: alert.metadata ?? {},
    });
    logger.info(`[BehavioralAlertConsumer] Routed alert ${alertId} to human review queue.`);
  } catch (err) {
    logger.error(
      `[BehavioralAlertConsumer] Failed to route alert ${alertId} to review queue.`,
      err
    );
  }
}

async function notifySafetyOncall(alertId: string, alert: BehavioralAlert): Promise<void> {
  try {
    const message: admin.messaging.Message = {
      topic: "safety-oncall",
      notification: {
        title: `Critical Safety Alert — ${alert.alertType}`,
        body: alert.targetUid
          ? `Target user: ${alert.targetUid}. Immediate review required.`
          : "Immediate review required.",
      },
      data: {
        alertId,
        alertType: alert.alertType,
        severity: alert.severity,
        senderUid: alert.senderUid ?? "",
        targetUid: alert.targetUid ?? "",
        deepLink: `amen://admin/review/${alertId}`,
      },
      android: { priority: "high" },
      apns: {
        payload: { aps: { "content-available": 1, sound: "default" } },
      },
    };

    await admin.messaging().send(message);
    logger.info(
      `[BehavioralAlertConsumer] FCM notification sent for critical alert ${alertId}.`
    );
  } catch (err) {
    logger.warn(
      `[BehavioralAlertConsumer] FCM notification failed for alert ${alertId} — ` +
        "alert is still in human review queue.",
      err
    );
  }
}
