// AmenBereanConversionModels.swift
// AMEN App — CommunityOS / Berean
//
// Phase 2 — Agent A4 (Berean Integration)
// Domain models for converting Berean AI outputs into canonical AMEN objects.
//
// Design principles:
//   - BereanCapture is the universal input to all conversion paths.
//   - BereanConversionResult carries full provenance and target coordinates.
//   - Provenance is always set on converted objects — source attribution is never stripped.
//   - No screenshot workflow: conversions go directly to Firestore via AmenBereanConversionService.
//
// SHARED TYPES (do NOT redefine here):
//   AmenIntent, SpawnProvenance  →  CommunityObjectTypes.swift
//   ComposerSource               →  CommunityOS/Composer/AmenComposerModels.swift

import Foundation

// MARK: - BereanAIOutputType

/// Describes which Berean AI output mode produced the captured content.
/// Stored as the `sourceType` discriminator in SpawnProvenance when writing
/// converted objects to Firestore. Raw value matches the Firestore field.
enum BereanAIOutputType: String, Codable, CaseIterable, Sendable {
    /// Berean answered a free-form theological question.
    case answer                = "bereanAnswer"
    /// A structured multi-week Bible study plan generated by Berean.
    case studyPlan             = "bereanStudyPlan"
    /// Deep single-passage scripture study output.
    case scriptureStudy        = "bereanScriptureStudy"
    /// Daily devotional content generated by Berean.
    case devotional            = "bereanDevotional"
    /// Prayer guide content generated by Berean.
    case prayerGuide           = "bereanPrayerGuide"
    /// Sermon outline generated by Berean.
    case sermonOutline         = "bereanSermonOutline"
    /// A selected excerpt from an ongoing Berean conversation.
    case conversationExcerpt   = "bereanConversationExcerpt"

    /// Human-readable label shown in provenance banners.
    var displayName: String {
        switch self {
        case .answer:              return "Berean Answer"
        case .studyPlan:           return "Berean Study Plan"
        case .scriptureStudy:      return "Berean Scripture Study"
        case .devotional:          return "Berean Devotional"
        case .prayerGuide:         return "Berean Prayer Guide"
        case .sermonOutline:       return "Berean Sermon Outline"
        case .conversationExcerpt: return "Berean Conversation"
        }
    }

    /// SF Symbol for use in banners and action pills.
    var systemImage: String {
        switch self {
        case .answer:              return "sparkle"
        case .studyPlan:           return "list.bullet.clipboard"
        case .scriptureStudy:      return "book.closed"
        case .devotional:          return "sun.max"
        case .prayerGuide:         return "hands.sparkles"
        case .sermonOutline:       return "list.bullet.rectangle"
        case .conversationExcerpt: return "bubble.left.and.bubble.right"
        }
    }
}

// MARK: - BereanCapture

/// A point-in-time capture of a Berean AI output, ready to be converted into
/// any canonical AMEN object without a screenshot workflow.
///
/// Created by the Berean chat / study surfaces; passed to `AmenBereanConversionService`
/// conversion methods. The `id` field must be unique per capture session so that
/// provenance back-links remain stable even if the source conversation is later
/// modified.
///
/// PRIVACY: `content` may contain sensitive spiritual content. It must not be
/// transmitted to third-party analytics systems. Persisted only as part of the
/// Firestore object it is converted into.
struct BereanCapture: Identifiable, Sendable {
    /// Stable unique identifier for this capture session.
    /// Used as the `sourceRef` in SpawnProvenance when `conversationRef` is nil.
    var id: String

    /// Which Berean output mode produced this content.
    var sourceType: BereanAIOutputType

    /// The full Berean text — answer, study body, devotional, prayer guide, etc.
    var content: String

    /// Optional human-readable title extracted from the content or provided by the user.
    /// When nil, conversion methods derive a title from the first sentence of `content`.
    var title: String?

    /// Scripture references detected or cited in the Berean output.
    /// e.g. ["John 3:16", "Romans 8:28"]
    var scriptureRefs: [String]

    /// Ordered outline points from a study plan or sermon outline.
    /// Non-empty only when `sourceType` is `.studyPlan` or `.sermonOutline`.
    var studyOutlinePoints: [String]

    /// The Berean conversation/session ID that produced this capture.
    /// Used as `sourceRef` in provenance when available; falls back to `id`.
    var conversationRef: String?

    /// Wall-clock time when the capture was created on the client.
    var capturedAt: Date

    // MARK: - Convenience

    /// Returns the best available title: explicit title if set, otherwise the
    /// first sentence of `content` (truncated to 80 characters).
    var resolvedTitle: String {
        if let explicit = title, !explicit.isEmpty {
            return explicit
        }
        let firstSentence = content
            .components(separatedBy: CharacterSet(charactersIn: ".!?\n"))
            .first?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? content
        return String(firstSentence.prefix(80))
    }

    /// The stable Firestore reference string for provenance.
    /// Prefers the conversation session ref; falls back to the capture id.
    var provenanceRef: String {
        "/bereanConversations/\(conversationRef ?? id)"
    }
}

// MARK: - BereanConversionResult

/// The outcome of a successful Berean-to-AMEN-object conversion.
///
/// Callers use `targetType` + `documentId` to navigate to the newly created object.
/// `provenance` is the same record written into the Firestore document — the UI layer
/// can use it to render `AmenBereanProvenanceBanner` without an extra Firestore read.
struct BereanConversionResult: Sendable {
    /// The Firestore collection of the created object (e.g. "posts", "prayers", "studies").
    var targetType: String

    /// The Firestore document ID of the newly created object.
    var documentId: String

    /// Provenance record that was written into the converted object.
    /// Never nil — every converted object carries Berean attribution.
    var provenance: SpawnProvenance

    /// The AmenIntent that drove this conversion.
    var intent: AmenIntent

    /// Human-readable description of what was created, for toast messages.
    /// e.g. "Saved to Posts", "Study room created", "Prayer request created"
    var successMessage: String {
        switch intent {
        case .share:    return "Shared as a post"
        case .discuss:  return "Discussion room created"
        case .pray:     return "Prayer request created"
        case .study:    return "Study room created"
        case .teach:    return "Teaching post created"
        case .ask:      return "Question sent"
        case .mentor:   return "Mentorship topic created"
        case .announce: return "Announcement created"
        case .invite:   return "Invite created"
        case .volunteer: return "Volunteer opportunity created"
        case .hire:     return "Job posting created"
        }
    }
}
