/**
 * catalogSchema.ts
 *
 * TypeScript interfaces for the AMEN Catalog + Knowledge Network Firestore
 * documents. These types match the frozen contracts §1.1–§1.7 defined in the
 * Catalog build (2026-06-06) and enforced by firestore.rules.
 *
 * Design rules:
 *   - Default state is private. visibility='public' requires CF transition.
 *   - Soft delete only: set deletedAt to a Firestore Timestamp; never hard-delete.
 *   - reviewState='published' is CF-only (Admin SDK). Clients cannot self-publish.
 *   - Server-side entitlement checks only — never trust client claims.
 *
 * All new Cloud Functions that read or write catalog documents must import
 * these types rather than defining their own inline shapes.
 */

import { Timestamp } from "firebase-admin/firestore";

// ---------------------------------------------------------------------------
// §1.1  Enumerations
// ---------------------------------------------------------------------------

/**
 * The content type of a catalog work.
 * Matches WorkType in CatalogModels.swift.
 */
export type WorkType =
  | "book"
  | "album"
  | "track"
  | "podcast"
  | "episode"
  | "video"
  | "sermon"
  | "article"
  | "course"
  | "event";

/**
 * Who can see a work.
 * Visibility is private at creation; public/followers/paid_members/organization
 * require an explicit creator action and CF-side enforcement.
 * Matches WorkVisibility in CatalogModels.swift.
 */
export type WorkVisibility =
  | "public"
  | "followers"
  | "paid_members"
  | "organization"
  | "private";

/**
 * Editorial state of a work. Clients may advance from 'imported' → 'draft' → 'review'.
 * 'approved' and 'published' transitions are CF-only (Admin SDK).
 * Matches WorkReviewState in CatalogModels.swift.
 */
export type WorkReviewState =
  | "imported"
  | "draft"
  | "review"
  | "approved"
  | "published";

/**
 * Status of an ingestion job. 'pending' is set by client; all subsequent
 * transitions ('running' | 'done' | 'error') are CF-only.
 */
export type IngestionJobStatus = "pending" | "running" | "done" | "error";

/**
 * Status of a verification claim. 'pending' is set by client;
 * 'approved' and 'rejected' are CF/Admin SDK only (no-self-approval invariant).
 */
export type VerificationClaimStatus = "pending" | "approved" | "rejected";

/**
 * Supported external source platforms for ingestion (connectSource callable).
 */
export type IngestionSourceProvider =
  | "spotify"
  | "apple_music"
  | "youtube"
  | "google_books"
  | "manual";

/**
 * Type of verification being claimed.
 * NOTE: 'verified_public_figure' is intentionally absent — requires human
 * product decision before it may be added (see VerificationBadgeView.swift).
 */
export type VerificationBadgeType =
  | "ministry_leader"
  | "nonprofit"
  | "church"
  | "independent_creator";

// ---------------------------------------------------------------------------
// §1.2  WorkLink — embedded sub-document
// ---------------------------------------------------------------------------

/**
 * An external link to a platform where this work is available.
 * Matches WorkLink in CatalogModels.swift.
 */
export interface WorkLink {
  /** Link category, e.g. 'stream', 'buy', 'download' */
  kind: string;
  /** Human-readable platform name, e.g. 'Spotify', 'Apple Books' */
  platform: string;
  /** Canonical URL to the work on the platform */
  url: string;
  /**
   * Affiliate-tagged URL for revenue sharing.
   * Backend only: never trust a client-supplied affiliate URL.
   * Must be generated by the backend after verifying ownership.
   */
  affiliateUrl?: string;
}

// ---------------------------------------------------------------------------
// §1.3  Work — /works/{workId}
// ---------------------------------------------------------------------------

/**
 * Firestore document shape for /works/{workId}.
 *
 * Firestore rules enforce:
 *   - CREATE: creatorId == caller, reviewState == 'imported', visibility == 'private',
 *             deletedAt == null, publishedAt absent.
 *   - UPDATE: creatorId immutable; reviewState cannot advance to 'approved'/'published'
 *             from client; publishedAt immutable from client; soft-delete only.
 *   - READ (non-owner): reviewState must be 'published' (P0-DRAFT-LEAK fix 2026-06-15).
 *   - DELETE: denied (soft-delete only via deletedAt).
 *
 * Matches CatalogWork in CatalogModels.swift.
 */
export interface Work {
  /** Firestore document ID (auto-generated) */
  id: string;
  /** UID of the creator who owns this work. Immutable after creation. */
  creatorId: string;
  /** Content type */
  type: WorkType;
  /** Display title */
  title: string;
  /** Optional subtitle (e.g. album artist, book author) */
  subtitle?: string;
  /** Freeform description or synopsis */
  description?: string;
  /** Storage URL for the cover art image */
  coverUrl?: string;
  /**
   * When the work was first published externally (may predate import).
   * CF-only: clients cannot set this field on create; it is set when
   * reviewState transitions to 'published'.
   */
  publishedAt?: Timestamp;
  /** External links to streaming/purchase platforms */
  links: WorkLink[];
  /** Taxonomy topics for discovery and KnowledgeNode linking */
  topics: string[];
  /** Who can see this work. Default: 'private' at creation. */
  visibility: WorkVisibility;
  /**
   * Editorial state. Default: 'imported' at creation.
   * 'published' is CF-only (Admin SDK).
   */
  reviewState: WorkReviewState;
  /**
   * True when the creator's ownership of this work has been verified
   * by an approved VerificationClaim. Set by CF only.
   */
  verifiedOwnership: boolean;
  /**
   * If visibility == 'organization', the org this work is restricted to.
   * Checked against the caller's orgId custom claim.
   */
  orgId?: string;
  /** Firestore server timestamp set on document creation. */
  createdAt: Timestamp;
  /**
   * Firestore server timestamp set on last update.
   * Updated by CF on every write that touches reviewState or visibility.
   */
  updatedAt: Timestamp;
  /**
   * Soft-delete timestamp. Null (absent) = active.
   * Clients may only set this from null → Timestamp (I-1).
   * Reversal (Timestamp → null) is blocked by Firestore rules.
   */
  deletedAt?: Timestamp;
}

// ---------------------------------------------------------------------------
// §1.4  KnowledgeNode — /knowledgeNodes/{nodeId}
// ---------------------------------------------------------------------------

/**
 * Firestore document shape for /knowledgeNodes/{nodeId}.
 *
 * Knowledge graph nodes linking topics to a creator's works for semantic
 * discovery and AskCreator queries.
 *
 * Firestore rules enforce:
 *   - READ: owner only (direct doc reads). CF handles public discovery queries
 *           after verifying work visibility.
 *   - CREATE/UPDATE: owner only; creatorId immutable.
 *   - DELETE: denied (I-1). Use deletedAt or CF-side cleanup.
 *
 * Matches KnowledgeNode in CatalogModels.swift.
 */
export interface KnowledgeNode {
  /** Firestore document ID (auto-generated) */
  id: string;
  /** UID of the creator who owns the knowledge graph. Immutable. */
  creatorId: string;
  /** Taxonomy topic this node represents */
  topic: string;
  /**
   * Number of works linked to this node.
   * Maintained by CF to avoid client-side increments.
   */
  workCount: number;
  /** Array of /works/{workId} document IDs linked to this topic */
  workRefs: string[];
  /** Firestore server timestamp set on creation */
  createdAt: Timestamp;
  /** Firestore server timestamp of last update */
  updatedAt: Timestamp;
  /**
   * Soft-delete timestamp (I-1).
   * CF may set this during cleanup; clients cannot update KnowledgeNode docs.
   */
  deletedAt?: Timestamp;
}

// ---------------------------------------------------------------------------
// §1.5  IngestionJob — /ingestionJobs/{jobId}
// ---------------------------------------------------------------------------

/**
 * Firestore document shape for /ingestionJobs/{jobId}.
 *
 * Tracks a provider import job (Spotify library sync, YouTube channel scan, etc.).
 *
 * Firestore rules enforce:
 *   - READ: job creator only.
 *   - CREATE: creator only; status must be 'pending'.
 *   - UPDATE: denied from client (CF Admin SDK advances status).
 *   - DELETE: denied (I-1).
 */
export interface IngestionJob {
  /** Firestore document ID (auto-generated) */
  id: string;
  /** UID of the creator who initiated the import. Immutable. */
  creatorId: string;
  /** Source platform being ingested */
  provider: IngestionSourceProvider;
  /**
   * Job lifecycle status.
   * 'pending' set by client; 'running'/'done'/'error' set by CF only.
   */
  status: IngestionJobStatus;
  /**
   * Number of works successfully imported.
   * Set by CF when status transitions to 'done'.
   */
  importedCount?: number;
  /**
   * Human-readable error message if status == 'error'.
   * Set by CF; never trust a client-supplied error value.
   */
  errorMessage?: string;
  /**
   * Opaque pagination cursor for resuming a partial import.
   * CF-only field; clients should not read or write this.
   */
  resumeCursor?: string;
  /** Firestore server timestamp set on job creation */
  createdAt: Timestamp;
  /**
   * Firestore server timestamp when the job completed (done or error).
   * Set by CF only.
   */
  completedAt?: Timestamp;
}

// ---------------------------------------------------------------------------
// §1.6  VerificationClaim — /verificationClaims/{claimId}
// ---------------------------------------------------------------------------

/**
 * Firestore document shape for /verificationClaims/{claimId}.
 *
 * Ownership/identity verification request submitted by a creator.
 *
 * Firestore rules enforce:
 *   - READ: claim owner OR executive_admin.
 *   - CREATE: owner only; status must be 'pending'; creatorId == caller.
 *   - UPDATE: denied from client (CF/Admin SDK handles approval).
 *   - DELETE: denied (I-1 — permanent audit record).
 *
 * No-self-approval invariant: the creator who submitted the claim cannot
 * be the reviewer. This is enforced by denying client updates entirely.
 */
export interface VerificationClaim {
  /** Firestore document ID (auto-generated) */
  id: string;
  /** UID of the creator making the claim. Immutable. */
  creatorId: string;
  /** Category of verification being requested */
  badgeType: VerificationBadgeType;
  /**
   * Claim lifecycle status.
   * 'pending' set by client; 'approved'/'rejected' set by CF/Admin SDK only.
   */
  status: VerificationClaimStatus;
  /**
   * Supporting documentation URLs (e.g. ministry registration, 501c3 letter).
   * Validated by CF; must be Firebase Storage URLs owned by the creator.
   */
  evidenceUrls: string[];
  /**
   * Free-text explanation from the creator (max 1000 characters, enforced by CF).
   */
  description?: string;
  /**
   * UID of the platform admin who reviewed this claim.
   * Set by CF only when status transitions to 'approved' or 'rejected'.
   */
  reviewedBy?: string;
  /**
   * Reviewer's decision notes (internal, not shown to creator).
   * Set by CF only.
   */
  reviewNotes?: string;
  /** Firestore server timestamp set on claim creation */
  createdAt: Timestamp;
  /**
   * Firestore server timestamp when the claim was reviewed.
   * Set by CF only.
   */
  reviewedAt?: Timestamp;
}

// ---------------------------------------------------------------------------
// §1.7  CatalogSubscription — /users/{uid}/followedTopics/{topicId}
// ---------------------------------------------------------------------------

/**
 * Firestore document shape for /users/{uid}/followedTopics/{topicId}.
 *
 * Records a user's topic subscription for the Knowledge Feed.
 *
 * Firestore rules enforce:
 *   - READ/WRITE/DELETE: owner only (uid == request.auth.uid).
 *   - DELETE IS permitted (unlike content objects) — unfollowing a topic
 *     is a preference record, not content (I-1 applies to content only).
 */
export interface CatalogSubscription {
  /** Topic identifier (matches Work.topics string values) */
  topicId: string;
  /** Display label for the topic (denormalised for UI rendering) */
  topicLabel: string;
  /** UID of the subscribing user. Must match the parent document path uid. */
  userId: string;
  /** Firestore server timestamp set when the subscription was created */
  followedAt: Timestamp;
}

// ---------------------------------------------------------------------------
// §1.8  Wire shapes for callable Cloud Functions
// ---------------------------------------------------------------------------

/**
 * Request payload for the askCreatorQuery callable.
 * The CF validates all fields server-side before passing to callModel.
 */
export interface AskCreatorQueryRequest {
  /** UID of the creator whose corpus to query */
  creatorId: string;
  /** Natural-language question from the user */
  question: string;
  /**
   * Optional workId to focus the query on a single work.
   * If absent, the full published corpus is searched.
   */
  focusWorkId?: string;
}

/**
 * Response payload from the askCreatorQuery callable.
 */
export interface AskCreatorQueryResponse {
  /** The model-generated answer grounded in the creator's works */
  answer: string;
  /**
   * Cited works used to ground the answer.
   * Empty array if no works were cited (e.g. refused or off-topic).
   */
  citations: AskCreatorCitation[];
  /** callModel task mode used */
  mode: string;
  /**
   * Model confidence score 0–1.
   * Values below 0.4 should surface a low-confidence UI indicator.
   */
  confidence: number;
  /**
   * True if the model refused to answer (safety or scope).
   * UI must show a fallback message; do NOT show the answer string.
   */
  refused: boolean;
}

/**
 * A single cited work within an AskCreatorQueryResponse.
 * Matches CatalogCitation in CatalogModels.swift.
 */
export interface AskCreatorCitation {
  /** Firestore document ID of the cited Work */
  workId: string;
  /** Short quoted snippet from the work */
  snippet: string;
  /** Canonical URL for linking to the work */
  sourceUrl: string;
  /** Per-citation confidence score 0–1 */
  confidence: number;
}
