import SwiftUI

/// The mandatory draft review gate — AI output is NEVER silently inserted into notes.
/// The user must explicitly Approve, Edit, or Reject each draft field.
/// Approved text is returned to the caller to insert via ChurchNoteBlockRepository.
struct ChurchNotesAIDraftReviewView: View {

    let job: ChurchNoteProcessingJob
    @ObservedObject var processingService: ChurchNotesMediaProcessingService
    var onApproved: (ChurchNoteDraftApprovalResult) -> Void
    var onDismiss: () -> Void

    @State private var selectedField: ChurchNoteDraftField?
    @State private var isApproving  = false
    @State private var isRejecting  = false
    @State private var isGenerating = false
    @State private var actionError: String?
    @State private var editedText: String = ""
    @State private var isEditing = false

    @Environment(\.accessibilityReduceTransparency) private var reduceTransparency
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    private var availableFields: [(ChurchNoteDraftField, String)] {
        job.availableDraftFields
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    approvalBanner
                    sourceAttribution
                    if availableFields.isEmpty {
                        emptyState
                    } else {
                        fieldPicker
                        if let field = selectedField,
                           let pair  = availableFields.first(where: { $0.0 == field }) {
                            draftContent(field: field, text: pair.1)
                        }
                    }
                    generationActions
                }
                .padding(20)
            }
            .background(Color(.systemBackground))
            .navigationTitle("Review Draft")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Done") { onDismiss() }
                        .accessibilityLabel("Done reviewing draft")
                }
            }
            .onAppear { selectedField = availableFields.first?.0 }
        }
    }

    // MARK: - Approval banner (always visible)

    private var approvalBanner: some View {
        HStack(spacing: 10) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(.orange)
                .accessibilityHidden(true)

            Text("AI-assisted draft — review carefully before adding to your notes.")
                .font(.callout)
                .foregroundStyle(.secondary)
        }
        .padding(12)
        .background(Color.orange.opacity(0.08), in: RoundedRectangle(cornerRadius: 12))
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Warning: AI-assisted draft. Review carefully before adding to your notes.")
    }

    // MARK: - Source attribution

    private var sourceAttribution: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 6) {
                Image(systemName: job.sourceType.sfSymbol)
                    .accessibilityHidden(true)
                Text("Source: \(job.sourceType.displayLabel)")
                if job.safetyStatus == "passed" {
                    Image(systemName: "checkmark.shield.fill")
                        .foregroundStyle(.green)
                        .accessibilityLabel("Safety check passed")
                }
            }
            HStack(spacing: 4) {
                Image(systemName: "sparkles")
                    .accessibilityHidden(true)
                Text("Draft generated by Claude AI (Anthropic) — review before inserting")
            }
        }
        .font(.caption)
        .foregroundStyle(.secondary)
    }

    // MARK: - Field picker

    @ViewBuilder
    private var fieldPicker: some View {
        if availableFields.count > 1 {
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 8) {
                    ForEach(availableFields, id: \.0) { field, _ in
                        let isSelected = selectedField == field
                        Button {
                            selectedField = field
                            editedText    = ""
                            isEditing     = false
                        } label: {
                            Text(field.displayLabel)
                                .font(.caption.weight(isSelected ? .semibold : .regular))
                                .padding(.horizontal, 12)
                                .padding(.vertical, 6)
                                .background(
                                    isSelected ? Color.accentColor : Color(.secondarySystemFill),
                                    in: Capsule()
                                )
                                .foregroundStyle(isSelected ? .white : .primary)
                        }
                        .accessibilityLabel("\(field.displayLabel)\(isSelected ? ", selected" : "")")
                    }
                }
                .padding(.horizontal, 2)
            }
        }
    }

    // MARK: - Draft content

    @ViewBuilder
    private func draftContent(field: ChurchNoteDraftField, text: String) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(field.displayLabel)
                .font(.headline)

            if isEditing {
                TextEditor(text: $editedText)
                    .frame(minHeight: 200)
                    .padding(8)
                    .background(Color(.secondarySystemFill), in: RoundedRectangle(cornerRadius: 10))
                    .font(.body)
                    .accessibilityLabel("Edit draft text for \(field.displayLabel)")
            } else {
                Text(text)
                    .font(.body)
                    .foregroundStyle(.primary)
                    .textSelection(.enabled)
                    .accessibilityLabel("Draft text: \(text.prefix(200))\(text.count > 200 ? "…" : "")")
            }

            if let err = actionError {
                Text(err)
                    .font(.callout)
                    .foregroundStyle(.red)
                    .accessibilityLabel("Error: \(err)")
            }

            // Action row
            HStack(spacing: 12) {
                approveButton(field: field, text: isEditing ? editedText : text)

                if reduceTransparency {
                    Button {
                        if isEditing {
                            isEditing  = false
                            editedText = ""
                        } else {
                            editedText = text
                            isEditing  = true
                        }
                    } label: {
                        Label(isEditing ? "Cancel Edit" : "Edit First", systemImage: isEditing ? "xmark" : "pencil")
                            .font(.subheadline)
                            .padding(.horizontal, 14)
                            .padding(.vertical, 8)
                            .background(Color(.secondarySystemFill), in: RoundedRectangle(cornerRadius: 10))
                    }
                    .accessibilityLabel(isEditing ? "Cancel editing" : "Edit draft before approving")
                } else {
                    Button {
                        if isEditing {
                            isEditing  = false
                            editedText = ""
                        } else {
                            editedText = text
                            isEditing  = true
                        }
                    } label: {
                        Label(isEditing ? "Cancel Edit" : "Edit First", systemImage: isEditing ? "xmark" : "pencil")
                            .font(.subheadline)
                            .padding(.horizontal, 14)
                            .padding(.vertical, 8)
                    }
                    .accessibilityLabel(isEditing ? "Cancel editing" : "Edit draft before approving")
                    .amenGlassEffect(in: RoundedRectangle(cornerRadius: 10, style: .continuous))
                    .animation(reduceMotion ? nil : .snappy, value: isEditing)
                }

                Spacer()

                rejectButton(field: field)
            }
        }
        .padding(16)
        .background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 14))
    }

    // MARK: - Approve / Reject buttons

    @ViewBuilder
    private func approveButton(field: ChurchNoteDraftField, text: String) -> some View {
        if isApproving {
            ProgressView()
                .padding(.horizontal, 16)
        } else {
            Button {
                Task { await approve(field: field, editedText: isEditing ? text : nil) }
            } label: {
                Label("Add to Notes", systemImage: "checkmark")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(.white)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 8)
                    .background(Color.accentColor, in: RoundedRectangle(cornerRadius: 10))
            }
            .disabled(isEditing && editedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            .accessibilityLabel("Approve and add to notes")
            .accessibilityHint("Inserts this draft into your church note as blocks")
        }
    }

    @ViewBuilder
    private func rejectButton(field: ChurchNoteDraftField) -> some View {
        if isRejecting {
            ProgressView()
        } else {
            Button {
                Task { await reject(field: field) }
            } label: {
                Image(systemName: "xmark")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                    .frame(width: 36, height: 36)
            }
            .background { if reduceTransparency { Circle().fill(Color(.systemBackground)) } }
            .amenGlassEffect(in: Circle())
            .accessibilityLabel("Reject this draft")
            .accessibilityHint("Rejects the draft without adding it to notes")
        }
    }

    // MARK: - Generation actions

    @ViewBuilder
    private var generationActions: some View {
        let flags = AMENFeatureFlags.shared
        let hasTranscript = job.transcriptText != nil || job.ocrText != nil

        if hasTranscript && (
            flags.sermonSummaryGenerationEnabled ||
            flags.churchNotesStudyGuideEnabled ||
            flags.churchNotesPrayerPromptsEnabled ||
            flags.sermonActionExtractionEnabled ||
            flags.scriptureDetectionEnabled ||
            flags.sermonClipSuggestionEnabled
        ) {
            VStack(alignment: .leading, spacing: 10) {
                Text("Generate more")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(.secondary)

                LazyVGrid(columns: [GridItem(.adaptive(minimum: 140), spacing: 10)], alignment: .leading, spacing: 10) {
                    if flags.sermonSummaryGenerationEnabled && job.summaryDraft == nil {
                        generateButton(label: "Summary", symbol: "text.badge.checkmark") {
                            Task { await generateSummary() }
                        }
                    }
                    if flags.churchNotesStudyGuideEnabled && job.studyGuideDraft == nil {
                        generateButton(label: "Study Guide", symbol: "book.fill") {
                            Task { await generateContent(.studyGuideDraft) }
                        }
                    }
                    if flags.churchNotesPrayerPromptsEnabled && job.prayerPromptsDraft == nil {
                        generateButton(label: "Prayer Prompts", symbol: "hands.sparkles.fill") {
                            Task { await generateContent(.prayerPromptsDraft) }
                        }
                    }
                    if flags.sermonActionExtractionEnabled {
                        generateButton(label: "Action Items", symbol: "checklist") {
                            Task { await runJobAction { try await processingService.generateActionItems(noteId: job.churchNoteId, jobId: job.id) } }
                        }
                    }
                    if flags.scriptureDetectionEnabled {
                        generateButton(label: "Scripture", symbol: "book.closed.fill") {
                            Task { await runJobAction { try await processingService.detectScriptures(noteId: job.churchNoteId, jobId: job.id) } }
                        }
                    }
                    if flags.sermonClipSuggestionEnabled && [.audio, .video].contains(job.sourceType) {
                        generateButton(label: "Clips", symbol: "film.stack") {
                            Task { await runJobAction { try await processingService.createClipSuggestions(noteId: job.churchNoteId, jobId: job.id) } }
                        }
                    }
                }
            }
            .padding(.top, 4)
        }
    }

    @ViewBuilder
    private func generateButton(label: String, symbol: String, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            if isGenerating {
                HStack(spacing: 6) {
                    ProgressView().scaleEffect(0.7)
                    Text(label)
                }
                .font(.callout)
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
            } else {
                Label(label, systemImage: symbol)
                    .font(.callout)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
            }
        }
        .disabled(isGenerating)
        .accessibilityLabel("Generate \(label)")
        .accessibilityHint("Generates AI-assisted \(label) draft from the transcript")
        .amenGlassEffect(in: RoundedRectangle(cornerRadius: 10, style: .continuous))
        .animation(reduceMotion ? nil : .amenSpringStandard, value: isGenerating)
    }

    // MARK: - Empty state

    private var emptyState: some View {
        VStack(spacing: 12) {
            Image(systemName: "doc.text.magnifyingglass")
                .font(.systemScaled(44))
                .foregroundStyle(.secondary)
                .accessibilityHidden(true)
            Text("No draft content is available yet.\nProcessing may still be in progress.")
                .font(.callout)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 32)
    }

    // MARK: - Actions

    private func approve(field: ChurchNoteDraftField, editedText userEdit: String?) async {
        isApproving = true
        actionError = nil

        do {
            var result = try await processingService.approveDraft(
                noteId: job.churchNoteId,
                jobId: job.id,
                draftField: field
            )
            // If user edited the text, override the server's returned text with the edited version.
            if let edited = userEdit, !edited.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                result = ChurchNoteDraftApprovalResult(
                    jobId: result.jobId, noteId: result.noteId,
                    draftField: result.draftField,
                    approvedText: edited,
                    sourceType: result.sourceType
                )
            }
            onApproved(result)
            isEditing  = false
            editedText = ""
        } catch {
            actionError = "Could not approve draft. Please try again."
        }
        isApproving = false
    }

    private func reject(field: ChurchNoteDraftField) async {
        isRejecting = true
        actionError = nil
        do {
            try await processingService.rejectDraft(
                noteId: job.churchNoteId,
                jobId: job.id,
                draftField: field
            )
        } catch {
            actionError = "Could not reject draft. Please try again."
        }
        isRejecting = false
    }

    private func generateSummary() async {
        await runJobAction {
            try await processingService.generateSummary(noteId: job.churchNoteId, jobId: job.id)
        }
    }

    private func generateContent(_ draftField: ChurchNoteDraftField) async {
        await runJobAction {
            switch draftField {
            case .studyGuideDraft:
                try await processingService.generateStudyGuide(noteId: job.churchNoteId, jobId: job.id)
            case .prayerPromptsDraft:
                try await processingService.generatePrayerPrompts(noteId: job.churchNoteId, jobId: job.id)
            default:
                break
            }
        }
    }

    private func runJobAction(_ action: () async throws -> Void) async {
        isGenerating = true
        actionError  = nil
        do {
            try await action()
        } catch {
            actionError = "Generation failed. Please try again."
        }
        isGenerating = false
    }
}
