import Foundation

// MARK: - BereanOSAIDisclosure
//
// This file extends the AI disclosure pattern for Berean OS.
// It provides a standalone disclosure model and does NOT modify AmenAIModels.swift.

/// A disclosure record that describes the epistemic status of AI-generated content
/// within the Berean OS truth-labelling pipeline.
struct BereanOSAIDisclosure: Codable, Equatable {

    /// The assessed confidence level for this piece of content.
    var confidenceLevel: BereanConfidenceLevel

    /// Zero or more human-readable warnings about this content's truthfulness.
    var truthWarnings: [String]

    /// Whether this content is speculative in nature.
    var isSpeculative: Bool

    /// The model or system that produced this content, e.g. `"gpt-4o-mini"` or `"berean-os"`.
    var generatedBy: String

    /// A human-readable disclosure string suitable for display directly to the user.
    var disclosureText: String

    // MARK: - Placeholder

    /// A safe placeholder used when real disclosure data is unavailable.
    static let placeholder = BereanOSAIDisclosure(
        confidenceLevel: .aiGenerated,
        truthWarnings: [],
        isSpeculative: false,
        generatedBy: "Berean OS",
        disclosureText: "This content was generated by AI. Please verify important claims."
    )
}
