// AskBereanWhyView.swift
// AMENAPP — Berean Spiritual Intelligence Layer (Wave 4)
//
// "Ask Berean Why" experience template.
// Five collapsible sections: Why Written / Why Here / Why Now / Why It Matters / Why I Care.
// Each section is generated by the REAL Berean Constitutional Pipeline
// (BereanPipelineClient → `bereanPipeline` callable). No simulation, no placeholder text:
// the displayed text is the pipeline's reviewed answer, or an honest error if it is
// unavailable / not consented / disabled.
//
// Depth dial: the live BereanDepthDialView controls the reasoning depth sent to the
// pipeline for every section. Changing it re-runs the loaded sections at the new depth.
//
// Citation integrity: any scripture-like token in a response passes through
// BereanCitationGate.guardedEmit(); unverifiable references are replaced with
// "[Citation could not be verified]".
//
// Guard: if askBereanWhyEnabled is false, renders ContentUnavailableView.

import SwiftUI

struct AskBereanWhyView: View {

    let passage: String

    @State private var sectionStates: [WhySection: SectionLoadState] = {
        var d = [WhySection: SectionLoadState]()
        WhySection.allCases.forEach { d[$0] = .idle }
        return d
    }()
    @State private var expandedSections: Set<WhySection> = [.whyWritten]
    @State private var showHowGeneratedSheet = false

    /// Live reasoning depth sent to the pipeline. Defaults to Deep Study (the
    /// historical posture of this template); the depth dial overrides it.
    @State private var selectedDepth: BereanDepth = .deep

    var body: some View {
        Group {
            if !AMENFeatureFlags.shared.askBereanWhyEnabled {
                ContentUnavailableView(
                    "Ask Berean Why is not enabled",
                    systemImage: "magnifyingglass.circle",
                    description: Text("This feature has not been activated for your account.")
                )
            } else {
                mainContent
            }
        }
    }

    // MARK: - Main Content

    private var mainContent: some View {
        ScrollView {
            LazyVStack(alignment: .leading, spacing: 16) {
                // Passage header
                passageHeader

                // Intent chip (transparency: shows the auto-selected posture)
                BereanIntentSwitchChip(
                    proposal: IntentProposal(
                        mode: .discern,
                        depth: selectedDepth,
                        confidence: 0.95,
                        rationale: "Examining why \(passage) was written",
                        autoSelected: true
                    ),
                    onOverride: { _ in }
                )
                .padding(.horizontal, 16)

                // Live depth dial — drives the depth sent to the pipeline.
                if AMENFeatureFlags.shared.longPressDepthDialEnabled {
                    depthDialSection
                }

                // Five collapsible why sections
                ForEach(WhySection.allCases, id: \.self) { section in
                    WhySectionCard(
                        section: section,
                        loadState: sectionStates[section] ?? .idle,
                        isExpanded: expandedSections.contains(section),
                        onToggle: { toggleSection(section) }
                    )
                    .padding(.horizontal, 16)
                }

                // Attribution footer
                attributionFooter
                    .padding(.horizontal, 16)
                    .padding(.bottom, 24)
            }
            .padding(.top, 16)
        }
        .background(Color(.systemGroupedBackground))
        .navigationTitle("Ask Berean Why")
        .navigationBarTitleDisplayMode(.inline)
        .sheet(isPresented: $showHowGeneratedSheet) {
            howGeneratedSheet
        }
        .task {
            // Lazy: load only the initially-expanded section. Other sections load
            // when the user opens them — this respects the pipeline rate limits
            // rather than firing five model calls at once.
            await loadExpandedSections()
        }
    }

    // MARK: - Passage Header

    private var passageHeader: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(passage.isEmpty ? "This passage" : passage)
                .font(.title2.weight(.bold))
                .foregroundStyle(Color(.label))
            Text("Why this passage matters")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .padding(.horizontal, 16)
    }

    // MARK: - Depth Dial Section

    private var depthDialSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Depth")
                .font(.subheadline.weight(.semibold))
                .foregroundStyle(.secondary)
                .padding(.leading, 4)

            BereanDepthDialView(
                currentDepth: selectedDepth,
                autoDepth: .deep,
                onSelect: { newDepth in
                    guard newDepth != selectedDepth else { return }
                    selectedDepth = newDepth
                    Task { await reloadForDepthChange() }
                }
            )
        }
        .padding(.horizontal, 16)
    }

    // MARK: - Attribution Footer

    private var attributionFooter: some View {
        HStack(spacing: 8) {
            Image(systemName: "sparkles")
                .font(.caption)
                .foregroundStyle(.secondary)
            Text("Summarized by Berean")
                .font(.caption)
                .foregroundStyle(.secondary)
            Button("How was this generated?") {
                showHowGeneratedSheet = true
            }
            .font(.caption)
            .foregroundStyle(.blue)
        }
    }

    // MARK: - How Generated Sheet

    private var howGeneratedSheet: some View {
        NavigationStack {
            ZStack {
                Color(.systemBackground).ignoresSafeArea()

                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        Text("How Berean Generated This")
                            .font(.title3.weight(.bold))

                        Text("Berean used the **Discern** and **Reflect** modes at **\(selectedDepth.displayLabel)** depth to analyse \(passage.isEmpty ? "this passage" : passage). Each section is produced by the Berean Constitutional Pipeline, which retrieves evidence, generates a candidate, and passes it through a doctrinal safety review before it is shown.")
                            .font(.body)

                        Text("Citation Integrity")
                            .font(.headline)
                        Text("Every scripture reference is verified through the Berean Citation Gate before display. References that cannot be verified are replaced with an amber warning.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)

                        Text("What Berean Does Not Do")
                            .font(.headline)
                        Text("Berean does not replace pastoral guidance, provide personal prophecy, or make doctrinal determinations for your church community.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                    .padding(20)
                }
            }
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { showHowGeneratedSheet = false }
                }
            }
        }
        .presentationDetents([.medium, .large])
        .presentationDragIndicator(.visible)
        .presentationBackground(.ultraThinMaterial)
    }

    // MARK: - Section Loading

    private func toggleSection(_ section: WhySection) {
        if expandedSections.contains(section) {
            expandedSections.remove(section)
        } else {
            expandedSections.insert(section)
            // Trigger load if not already started (idle or previously failed → retry).
            switch sectionStates[section] ?? .idle {
            case .idle, .failed:
                Task { await loadSection(section) }
            default:
                break
            }
        }
    }

    /// Loads only the sections that are currently expanded.
    private func loadExpandedSections() async {
        for section in WhySection.allCases where expandedSections.contains(section) {
            await loadSection(section)
        }
    }

    /// Depth changed — invalidate every section and reload the open ones at the new depth.
    private func reloadForDepthChange() async {
        for section in WhySection.allCases {
            sectionStates[section] = .idle
        }
        await loadExpandedSections()
    }

    private func loadSection(_ section: WhySection) async {
        // Only (re)load when idle or after a prior failure.
        switch sectionStates[section] ?? .idle {
        case .loading, .loaded:
            return
        case .idle, .failed:
            break
        }

        sectionStates[section] = .loading

        do {
            let query = BereanPipelineClient.BereanQuery(
                query: section.query(for: passage),
                mode: section.mode,
                userId: BereanPipelineClient.currentUserId,
                conversationHistory: nil,
                depth: selectedDepth
            )
            let response = try await BereanPipelineClient.shared.sendQuery(query)
            let guarded = await guardCitations(in: response.answer)
            sectionStates[section] = .loaded(AttributedContent(text: guarded))
        } catch {
            // Honest failure — surface the real reason (disabled / consent / unavailable),
            // never a fabricated answer.
            let message = (error as? LocalizedError)?.errorDescription
                ?? "Berean is unavailable right now. Tap to retry."
            sectionStates[section] = .failed(message)
        }
    }

    // MARK: - Citation Gate

    /// Scans the answer for scripture-like references and verifies each through the
    /// citation gate, replacing any that cannot be verified.
    private func guardCitations(in answer: String) async -> String {
        let tokens = answer.split(separator: " ", omittingEmptySubsequences: false).map(String.init)
        var result = ""
        for token in tokens {
            if looksLikeScriptureRef(token) {
                let (_, shouldBlock) = await BereanCitationGate.guardedEmit(
                    reference: token,
                    quotation: token,
                    depth: selectedDepth
                )
                if shouldBlock {
                    result += "[Citation could not be verified] "
                    continue
                }
            }
            result += token + " "
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Rough heuristic — matches "John 3:16", "1 Cor 13:4" style tokens.
    private func looksLikeScriptureRef(_ text: String) -> Bool {
        let pattern = #"\b\d?\s?[A-Z][a-z]+\s\d+:\d+"#
        return text.range(of: pattern, options: .regularExpression) != nil
    }
}

// MARK: - WhySectionCard

private struct WhySectionCard: View {

    let section: WhySection
    let loadState: SectionLoadState
    let isExpanded: Bool
    let onToggle: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header row
            Button(action: onToggle) {
                HStack {
                    Image(systemName: section.icon)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(.blue)
                        .frame(width: 24)

                    Text(section.title)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(Color(.label))

                    Spacer()

                    Image(systemName: isExpanded ? "chevron.up" : "chevron.down")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 16)
                .padding(.vertical, 14)
            }
            .buttonStyle(.plain)

            if isExpanded {
                Divider()
                    .padding(.horizontal, 16)

                sectionBody
                    .padding(16)
            }
        }
        .background(Color(.systemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
    }

    @ViewBuilder
    private var sectionBody: some View {
        switch loadState {
        case .idle, .loading:
            skeletonView
        case .loaded(let content):
            Text(content.text)
                .font(.subheadline)
                .foregroundStyle(Color(.label))
                .fixedSize(horizontal: false, vertical: true)
        case .failed(let message):
            VStack(alignment: .leading, spacing: 6) {
                Text(message)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                Text("Tap the section header to retry.")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            }
        }
    }

    private var skeletonView: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(0..<3, id: \.self) { i in
                RoundedRectangle(cornerRadius: 4, style: .continuous)
                    .fill(Color(.systemFill))
                    .frame(height: 13)
                    .frame(maxWidth: i == 2 ? .infinity * 0.65 : .infinity)
                    .redacted(reason: .placeholder)
            }
        }
    }
}

// MARK: - Supporting Types

enum WhySection: CaseIterable {
    case whyWritten
    case whyHere
    case whyNow
    case whyItMatters
    case whyICare

    var title: String {
        switch self {
        case .whyWritten:    return "Why Written"
        case .whyHere:       return "Why Here"
        case .whyNow:        return "Why Now"
        case .whyItMatters:  return "Why It Matters"
        case .whyICare:      return "Why I Care"
        }
    }

    var icon: String {
        switch self {
        case .whyWritten:    return "pencil.and.scribble"
        case .whyHere:       return "mappin.and.ellipse"
        case .whyNow:        return "clock.arrow.circlepath"
        case .whyItMatters:  return "star"
        case .whyICare:      return "heart"
        }
    }

    /// Posture mode for the pipeline. Reflective sections use Reflect; the rest Discern.
    var mode: BereanPipelineClient.BereanMode {
        switch self {
        case .whyNow, .whyICare: return .reflect
        default:                 return .discern
        }
    }

    /// Builds the natural-language question sent to the pipeline for this section.
    func query(for passage: String) -> String {
        let p = passage.isEmpty ? "this passage" : passage
        switch self {
        case .whyWritten:
            return "Why was \(p) written? Explain the human author, the original audience, and the occasion or purpose behind it."
        case .whyHere:
            return "What is the literary and canonical context of \(p)? Why does it appear where it does in Scripture, and how does it connect to what surrounds it?"
        case .whyNow:
            return "Why does \(p) still matter today? How is it relevant to a believer's life in the present?"
        case .whyItMatters:
            return "What is the theological significance of \(p)? Why does this passage matter for Christian faith and doctrine?"
        case .whyICare:
            return "Help me reflect personally on \(p). How might it shape my own devotion, prayer, and daily life?"
        }
    }
}

enum SectionLoadState: Equatable {
    case idle
    case loading
    case loaded(AttributedContent)
    case failed(String)
}

struct AttributedContent: Equatable {
    let text: String

    static func == (lhs: AttributedContent, rhs: AttributedContent) -> Bool {
        lhs.text == rhs.text
    }
}

// MARK: - Citation Warning Inline View

/// Drop-in replacement when a citation is blocked by BereanCitationGate.
struct BereanCitationBlockedLabel: View {
    var body: some View {
        Text("[Citation could not be verified]")
            .font(.subheadline.italic())
            .foregroundStyle(.orange)
    }
}
