// BereanAIConsentSheet.swift
// AMENAPP
//
// PRIV-005 fix: first-run AI consent disclosure for Berean.
// Shown the first time a user invokes any Berean AI surface. The pipeline
// refuses to call the model until consent is recorded (see
// BereanConstitutionalPipeline.ask + BereanAIConsentManager).

import SwiftUI

struct BereanAIConsentSheet: View {
    let onAccept: () -> Void
    let onDecline: () -> Void

    @State private var isSaving = false
    @State private var consentSaveError: String?

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 28) {

                    // MARK: — Icon + Title
                    HStack {
                        Spacer()
                        VStack(spacing: 12) {
                            ZStack {
                                Circle()
                                    .fill(Color.accentColor.opacity(0.12))
                                    .frame(width: 72, height: 72)
                                Image(systemName: "sparkles")
                                    .font(.systemScaled(32, weight: .semibold))
                                    .foregroundStyle(Color.accentColor)
                            }
                            .accessibilityHidden(true)

                            Text("About Berean AI")
                                .font(.title2)
                                .fontWeight(.bold)
                                .multilineTextAlignment(.center)

                            Text("Berean uses AI to help you study Scripture. Before you begin, here's exactly how it works and what happens to what you type.")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                                .multilineTextAlignment(.center)
                        }
                        Spacer()
                    }

                    Divider()

                    // MARK: — What Berean does
                    VStack(alignment: .leading, spacing: 16) {
                        Label {
                            Text("How Berean works")
                                .font(.headline)
                        } icon: {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundStyle(.green)
                        }

                        bulletRow(
                            icon: "sparkles",
                            iconColor: .purple,
                            title: "AI-generated responses",
                            detail: "Berean's answers are generated by AI and may contain errors. Always verify them against Scripture — Berean is a study aid, not an authority."
                        )

                        bulletRow(
                            icon: "network",
                            iconColor: .blue,
                            title: "Processed on our servers",
                            detail: "What you type is sent to AMEN's safety-reviewed AI service to produce a response. It is not used to train AI models."
                        )

                        bulletRow(
                            icon: "checkmark.shield",
                            iconColor: .green,
                            title: "Reviewed for safety",
                            detail: "Every response passes a constitutional review stage before it reaches you, and crisis signals are handled with care resources."
                        )
                    }

                    Divider()

                    // MARK: — What we never do
                    VStack(alignment: .leading, spacing: 16) {
                        Label {
                            Text("What we never do")
                                .font(.headline)
                        } icon: {
                            Image(systemName: "xmark.circle.fill")
                                .foregroundStyle(.red)
                        }

                        doNotRow(
                            icon: "brain",
                            text: "Use your questions to train AI models or build advertising profiles."
                        )
                        doNotRow(
                            icon: "person.2.slash",
                            text: "Share what you type with third parties, advertisers, or other users."
                        )
                    }

                    Divider()

                    // MARK: — Privacy note
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: "info.circle")
                            .foregroundStyle(.secondary)
                            .font(.footnote)
                            .padding(.top, 2)
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Your choice")
                                .font(.footnote)
                                .fontWeight(.semibold)
                                .foregroundStyle(.secondary)
                            Text("If you decline, Berean AI stays off and nothing you type is sent for AI processing. You can turn it on later from any Berean screen.")
                                .font(.footnote)
                                .foregroundStyle(.secondary)
                        }
                    }
                    .padding(12)
                    .background(
                        RoundedRectangle(cornerRadius: 10, style: .continuous)
                            .fill(Color(.secondarySystemBackground))
                    )

                    // MARK: — Actions
                    VStack(spacing: 12) {
                        if let errorMsg = consentSaveError {
                            HStack(spacing: 8) {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundStyle(.red)
                                    .font(.subheadline)
                                Text(errorMsg)
                                    .font(.subheadline)
                                    .foregroundStyle(.red)
                            }
                            .padding(12)
                            .background(
                                RoundedRectangle(cornerRadius: 10, style: .continuous)
                                    .fill(Color.red.opacity(0.08))
                            )
                        }

                        Button {
                            save(granted: true)
                        } label: {
                            Group {
                                if isSaving {
                                    HStack(spacing: 8) {
                                        ProgressView().tint(.white)
                                        Text("Saving…")
                                    }
                                } else {
                                    Text("I understand, continue")
                                }
                            }
                            .fontWeight(.semibold)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                            .background(Color.accentColor)
                            .foregroundStyle(.white)
                            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
                        }
                        .disabled(isSaving)
                        .accessibilityLabel("Accept Berean AI and continue")
                        .accessibilityHint("AI will generate study responses from what you type. You can turn this off later.")

                        Button {
                            save(granted: false)
                        } label: {
                            Text("Not now")
                                .fontWeight(.medium)
                                .frame(maxWidth: .infinity)
                                .padding(.vertical, 14)
                                .background(Color(.secondarySystemBackground))
                                .foregroundStyle(.primary)
                                .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
                        }
                        .disabled(isSaving)
                        .accessibilityLabel("Decline Berean AI")
                        .accessibilityHint("Berean AI stays off and nothing you type is sent for AI processing.")
                    }
                }
                .padding(.horizontal, 20)
                .padding(.vertical, 24)
            }
            .navigationBarTitleDisplayMode(.inline)
        }
    }

    // MARK: — Save

    private func save(granted: Bool) {
        guard !isSaving else { return }
        isSaving = true
        consentSaveError = nil
        Task {
            do {
                try await BereanAIConsentManager.shared.recordConsent(granted)
                if granted { onAccept() } else { onDecline() }
            } catch {
                consentSaveError = "Could not save your preference. Please try again."
            }
            isSaving = false
        }
    }

    // MARK: — Helpers

    @ViewBuilder
    private func bulletRow(icon: String, iconColor: Color, title: String, detail: String) -> some View {
        HStack(alignment: .top, spacing: 14) {
            Image(systemName: icon)
                .font(.systemScaled(20))
                .foregroundStyle(iconColor)
                .frame(width: 28)
                .accessibilityHidden(true)
            VStack(alignment: .leading, spacing: 3) {
                Text(title)
                    .font(.subheadline)
                    .fontWeight(.semibold)
                Text(detail)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    @ViewBuilder
    private func doNotRow(icon: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 14) {
            Image(systemName: icon)
                .font(.systemScaled(18))
                .foregroundStyle(.red.opacity(0.8))
                .frame(width: 28)
                .accessibilityHidden(true)
            Text(text)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}

// MARK: - Reusable gate modifier

extension View {
    /// Presents the first-run Berean AI consent sheet whenever the pipeline reports
    /// `requiresAIConsent`. Attach to any Berean entry surface. The hard refusal lives
    /// in BereanConstitutionalPipeline.ask, so this modifier only drives the UX.
    func bereanAIConsentGate() -> some View {
        modifier(BereanAIConsentGateModifier())
    }
}

private struct BereanAIConsentGateModifier: ViewModifier {
    @ObservedObject private var pipeline = BereanConstitutionalPipeline.shared

    func body(content: Content) -> some View {
        content
            .sheet(isPresented: Binding(
                get: { pipeline.requiresAIConsent },
                set: { if !$0 { pipeline.requiresAIConsent = false } }
            )) {
                BereanAIConsentSheet(
                    onAccept: { pipeline.requiresAIConsent = false },
                    onDecline: { pipeline.requiresAIConsent = false }
                )
            }
    }
}

#if DEBUG
#Preview {
    BereanAIConsentSheet(onAccept: {}, onDecline: {})
}
#endif
