import Foundation
import FirebaseFunctions

// MARK: - Models

/// A single daily brief generated by callModelDailyBrief (Gemini, failover to OpenAI).
struct DailyBrief: Codable, Identifiable {
    var id: String { dateKey }

    /// ISO-8601 date string (yyyy-MM-dd) used as the cache key.
    var dateKey: String = ""

    let greeting: String?
    let dailyVerse: String?
    let prayerReminder: String?
    let reflectionQuestion: String?
    let suggestedAction: String?

    enum CodingKeys: String, CodingKey {
        case greeting, dailyVerse, prayerReminder, reflectionQuestion, suggestedAction
    }

    /// True when all key fields are present and non-empty.
    var isComplete: Bool {
        [greeting, dailyVerse, prayerReminder, reflectionQuestion, suggestedAction]
            .compactMap { $0 }
            .filter { !$0.isEmpty }
            .count >= 3
    }

    static let placeholder = DailyBrief(
        greeting: "Good morning!",
        dailyVerse: nil,
        prayerReminder: nil,
        reflectionQuestion: nil,
        suggestedAction: nil
    )
}

/// Full response envelope from callModelDailyBrief.
private struct DailyBriefCallableResponse: Codable {
    let brief: DailyBrief?
    let degraded: Bool?
    let provider: String?
    let latencyMs: Int?
}

// MARK: - Errors

enum DailyDigestError: LocalizedError {
    case consentRequired
    case rateLimitExceeded
    case networkError(String)
    case serviceUnavailable

    var errorDescription: String? {
        switch self {
        case .consentRequired:      return "Enable Daily Brief in Settings to receive your morning digest."
        case .rateLimitExceeded:    return "You've already received your daily brief. Check back tomorrow."
        case .networkError(let m):  return "Could not load your brief: \(m)"
        case .serviceUnavailable:   return "Daily Brief is temporarily unavailable. Try again in a few minutes."
        }
    }
}

// MARK: - Service

/// Fetches the personalized Daily Brief via the `callModelDailyBrief` Firebase Function.
///
/// The callable routes through the centralized callModel router (Gemini primary, failover
/// to OpenAI, NVIDIA output guard). Responses are cached in UserDefaults for the calendar
/// day so at most one network call is made per day per user.
///
/// No API keys on device. All AI calls are server-side.
@MainActor
final class DailyDigestService: ObservableObject {

    static let shared = DailyDigestService()
    private let functions = Functions.functions(region: "us-central1")

    @Published var currentBrief: DailyBrief?
    @Published var isLoading = false
    @Published var lastError: DailyDigestError?

    private init() {
        loadCachedBrief()
    }

    // MARK: - Cache helpers

    private static var utcDayKey: String {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.timeZone = TimeZone(identifier: "UTC")
        return fmt.string(from: Date())
    }

    private static var cacheKey: String {
        "dailyBrief_\(utcDayKey)"
    }

    private func loadCachedBrief() {
        guard let data = UserDefaults.standard.data(forKey: Self.cacheKey),
              var brief = try? JSONDecoder().decode(DailyBrief.self, from: data) else { return }
        brief.dateKey = Self.utcDayKey
        currentBrief = brief
    }

    private func cacheBrief(_ brief: DailyBrief) {
        guard let data = try? JSONEncoder().encode(brief) else { return }
        UserDefaults.standard.set(data, forKey: Self.cacheKey)
    }

    // MARK: - Public API

    /// Fetch today's Daily Brief. Returns the cached version if already loaded today.
    ///
    /// - Parameter forceRefresh: If `true`, bypasses the daily cache and makes a new
    ///   network call. Use sparingly; the server rate-limits to 5 per user per day.
    @discardableResult
    func fetchBrief(forceRefresh: Bool = false) async throws -> DailyBrief {
        // Return cache if present and not forcing refresh
        if !forceRefresh, let cached = currentBrief, cached.isComplete {
            return cached
        }

        // Consent gate
        guard UserDefaults.standard.bool(forKey: "consentDailyBrief") else {
            throw DailyDigestError.consentRequired
        }

        isLoading = true
        lastError = nil
        defer { isLoading = false }

        // Build a lightweight user-context summary (privacy-respecting: no PII).
        let userSummary = buildUserSummary()
        let dateStr = Self.utcDayKey

        let payload: [String: Any] = [
            "userSummary": userSummary,
            "dateStr": dateStr,
        ]

        let result: HTTPSCallableResult
        do {
            result = try await functions
                .httpsCallable("callModelDailyBrief")
                .call(payload)
        } catch {
            let err = DailyDigestError.networkError(error.localizedDescription)
            lastError = err
            throw err
        }

        guard let raw = result.data as? [String: Any] else {
            lastError = .serviceUnavailable
            throw DailyDigestError.serviceUnavailable
        }

        let data = try JSONSerialization.data(withJSONObject: raw)
        let response = try JSONDecoder().decode(DailyBriefCallableResponse.self, from: data)

        // Degraded response: router returned a fallback result.
        if response.degraded == true || response.brief == nil {
            let fallback = DailyBrief(
                greeting: "Good morning! Take a moment to reflect on today.",
                dailyVerse: nil,
                prayerReminder: "Set aside time for prayer today.",
                reflectionQuestion: "What is one thing you're grateful for?",
                suggestedAction: "Read a chapter from Psalms."
            )
            currentBrief = fallback
            cacheBrief(fallback)
            return fallback
        }

        var brief = response.brief!
        brief.dateKey = Self.utcDayKey
        currentBrief = brief
        cacheBrief(brief)
        return brief
    }

    // MARK: - Private helpers

    /// Builds a short, PII-free summary string for brief personalization.
    /// Only uses anonymized preference data — never names, emails, or location.
    private func buildUserSummary() -> String {
        var parts: [String] = []

        // Reading streak (from UserDefaults — set by reading tracker)
        let readingDays = UserDefaults.standard.integer(forKey: "readingStreak")
        if readingDays > 0 {
            parts.append("reading streak: \(readingDays) days")
        }

        // Preferred Bible book (set during onboarding)
        if let book = UserDefaults.standard.string(forKey: "preferredBibleBook"), !book.isEmpty {
            parts.append("current study: \(book)")
        }

        // Prayer reminders enabled
        if UserDefaults.standard.bool(forKey: "prayerRemindersEnabled") {
            parts.append("prayer reminders: on")
        }

        return parts.isEmpty ? "faithful community member" : parts.joined(separator: ", ")
    }
}
