// CommunityEmergenceViewModel.swift
// AMEN App — Community Around Content OS
//
// Drives UI state for community emergence events: newly formed communities,
// recommended communities, and the user's joined communities.

import Foundation
import SwiftUI
import FirebaseAuth

// MARK: - CommunityEmergenceViewModel

@MainActor
final class CommunityEmergenceViewModel: ObservableObject {

    // MARK: Published State

    /// Set when a community has just emerged for the content being viewed.
    /// Drives the floating emergence banner.
    @Published var newlyEmergedCommunity: CommunityNode?

    /// Communities the system recommends based on engagement signals.
    @Published var recommendedCommunities: [CommunityNode] = []

    /// Communities the current user has already joined.
    @Published var joinedCommunities: [CommunityNode] = []

    /// True while any async operation is in-flight.
    @Published var isLoading = false

    // MARK: Private

    private let engine = CommunityEmergenceEngine.shared

    // MARK: - Emergence Check

    /// Evaluates the given content object for community emergence.
    /// If a new community forms, populates `newlyEmergedCommunity` and triggers haptic feedback.
    func checkEmergence(for contentObject: ContentObject) async {
        guard CommunityOSFlagService.shared.isEnabled(.autoEmergence) else { return }

        do {
            guard let node = try await engine.evaluateAndEmerge(contentObject: contentObject) else {
                return
            }

            // Only surface the banner for a freshly created community (within the last 60 seconds).
            let isNew = Date().timeIntervalSince(node.createdAt) < 60
            guard isNew else { return }

            let generator = UINotificationFeedbackGenerator()
            generator.notificationOccurred(.success)
            withAnimation(AppAnimation.stateChange) {
                newlyEmergedCommunity = node
            }
            dlog("[CommunityEmergenceViewModel] New community emerged: \(node.name)")
        } catch {
            dlog("[CommunityEmergenceViewModel] checkEmergence error: \(error)")
        }
    }

    // MARK: - Join / Leave

    /// Joins the given community. On success, moves the node from recommended to joined.
    func joinCommunity(_ node: CommunityNode) async {
        guard CommunityOSFlagService.shared.isEnabled(.autoEmergence) else { return }
        guard let userId = Auth.auth().currentUser?.uid else {
            dlog("[CommunityEmergenceViewModel] joinCommunity — no authenticated user")
            return
        }

        do {
            try await engine.joinCommunity(communityId: node.id, userId: userId)
            withAnimation(AppAnimation.stateChange) {
                recommendedCommunities.removeAll { $0.id == node.id }

                // Optimistic local increment so the UI responds instantly.
                let joined = CommunityNode(
                    id: node.id,
                    contentObjectId: node.contentObjectId,
                    contentKind: node.contentKind,
                    name: node.name,
                    memberCount: node.memberCount + 1,
                    discussionCount: node.discussionCount,
                    prayerCount: node.prayerCount,
                    testimonyCount: node.testimonyCount,
                    churchCount: node.churchCount,
                    eventCount: node.eventCount,
                    isAutoGenerated: node.isAutoGenerated,
                    activeLayers: node.activeLayers,
                    createdAt: node.createdAt,
                    lastActiveAt: node.lastActiveAt
                )
                if !joinedCommunities.contains(where: { $0.id == joined.id }) {
                    joinedCommunities.insert(joined, at: 0)
                }
            }
            dlog("[CommunityEmergenceViewModel] Joined community \(node.id)")
        } catch {
            dlog("[CommunityEmergenceViewModel] joinCommunity error: \(error)")
        }
    }

    // MARK: - Load Joined Communities

    /// Fetches the full list of communities the user is part of or might care about.
    func loadJoinedCommunities() async {
        guard CommunityOSFlagService.shared.isEnabled(.autoEmergence) else { return }
        guard let userId = Auth.auth().currentUser?.uid else {
            dlog("[CommunityEmergenceViewModel] loadJoinedCommunities — no authenticated user")
            return
        }

        isLoading = true
        defer {
            withAnimation(AppAnimation.fade) {
                isLoading = false
            }
        }

        do {
            let nodes = try await engine.fetchAllNodes(for: userId, limit: 50)

            // Partition into joined vs. recommended by checking membership for each node.
            var joined: [CommunityNode] = []
            var recommended: [CommunityNode] = []

            await withTaskGroup(of: (CommunityNode, Bool).self) { group in
                for node in nodes {
                    let nodeId = node.id
                    group.addTask {
                        let hasJoined = await self.engine.hasUserJoined(
                            communityId: nodeId,
                            userId: userId
                        )
                        return (node, hasJoined)
                    }
                }
                for await (node, hasJoined) in group {
                    if hasJoined {
                        joined.append(node)
                    } else {
                        recommended.append(node)
                    }
                }
            }

            withAnimation(AppAnimation.stateChange) {
                joinedCommunities = joined.sorted { $0.lastActiveAt > $1.lastActiveAt }
                recommendedCommunities = recommended.sorted { $0.memberCount > $1.memberCount }
            }
            dlog("[CommunityEmergenceViewModel] Loaded \(joined.count) joined + \(recommended.count) recommended communities")
        } catch {
            dlog("[CommunityEmergenceViewModel] loadJoinedCommunities error: \(error)")
        }
    }

    // MARK: - Dismiss

    /// Clears the emergence banner with an animated fade.
    func dismissEmergenceNotification() {
        withAnimation(AppAnimation.fade) {
            newlyEmergedCommunity = nil
        }
    }
}
