// CommunityEmergenceEngine.swift
// AMEN App — Community Around Content OS
//
// Actor that evaluates ContentObjects against emergence thresholds and
// creates CommunityNodes when those thresholds are crossed.
//
// Firestore paths:
//   communityNodes/{communityId}
//   contentObjects/{contentId}/emergenceLog/{logId}

import Foundation
import FirebaseFirestore
import FirebaseAuth

// MARK: - EmergenceLogEntry

/// Immutable record written to Firestore when a community is auto-created.
private struct EmergenceLogEntry: Codable {
    let id: String
    let contentObjectId: String
    let communityId: String
    let triggeredAt: Date
    let triggerReason: String

    init(
        id: String = UUID().uuidString,
        contentObjectId: String,
        communityId: String,
        triggeredAt: Date = Date(),
        triggerReason: String
    ) {
        self.id = id
        self.contentObjectId = contentObjectId
        self.communityId = communityId
        self.triggeredAt = triggeredAt
        self.triggerReason = triggerReason
    }

    var firestoreData: [String: Any] {
        [
            "id": id,
            "contentObjectId": contentObjectId,
            "communityId": communityId,
            "triggeredAt": Timestamp(date: triggeredAt),
            "triggerReason": triggerReason
        ]
    }
}

// MARK: - CommunityEmergenceEngine

actor CommunityEmergenceEngine {

    // MARK: Singleton

    static let shared = CommunityEmergenceEngine()

    // MARK: Private

    private let db = Firestore.firestore()

    private init() {}

    // MARK: - Public API

    /// Evaluates whether `contentObject` has crossed any emergence threshold.
    /// If thresholds are met and no community exists yet, creates a new CommunityNode.
    /// Returns the newly created node, the existing node, or nil if thresholds are not met.
    func evaluateAndEmerge(contentObject: ContentObject) async throws -> CommunityNode? {
        guard await CommunityOSFlagService.shared.isEnabled(.autoEmergence) else {
            dlog("[CommunityEmergenceEngine] autoEmergence flag is OFF — skipping evaluation for \(contentObject.id)")
            return nil
        }

        // Check if a community already exists for this content.
        if let existing = try await fetchCommunityNode(for: contentObject.id) {
            dlog("[CommunityEmergenceEngine] Community already exists for content \(contentObject.id): \(existing.id)")
            return existing
        }

        // Evaluate thresholds.
        guard meetsEmergenceThreshold(contentObject) else {
            dlog("[CommunityEmergenceEngine] Content \(contentObject.id) does not yet meet emergence thresholds")
            return nil
        }

        dlog("[CommunityEmergenceEngine] Emergence threshold crossed for \(contentObject.id) — creating community")
        let node = try await createCommunityNode(for: contentObject)
        return node
    }

    /// Builds a CommunityNode from a ContentObject, persists it to Firestore,
    /// and writes a log entry under the content object.
    func createCommunityNode(for contentObject: ContentObject) async throws -> CommunityNode {
        let communityId = UUID().uuidString
        let layers = contentObject.kind.defaultCommunityLayers
        let name = communityName(for: contentObject)

        let node = CommunityNode(
            id: communityId,
            contentObjectId: contentObject.id,
            contentKind: contentObject.kind,
            name: name,
            memberCount: 0,
            discussionCount: contentObject.discussionCount,
            prayerCount: contentObject.prayerCount,
            testimonyCount: contentObject.testimonyCount,
            churchCount: 0,
            eventCount: 0,
            isAutoGenerated: true,
            activeLayers: layers,
            createdAt: Date(),
            lastActiveAt: Date()
        )

        let nodeData: [String: Any] = [
            "id": node.id,
            "contentObjectId": node.contentObjectId,
            "contentKind": node.contentKind.rawValue,
            "name": node.name,
            "memberCount": node.memberCount,
            "discussionCount": node.discussionCount,
            "prayerCount": node.prayerCount,
            "testimonyCount": node.testimonyCount,
            "churchCount": node.churchCount,
            "eventCount": node.eventCount,
            "isAutoGenerated": node.isAutoGenerated,
            "activeLayers": node.activeLayers.map { $0.rawValue },
            "createdAt": Timestamp(date: node.createdAt),
            "lastActiveAt": Timestamp(date: node.lastActiveAt)
        ]

        try await db.collection("communityNodes").document(communityId).setData(nodeData)
        dlog("[CommunityEmergenceEngine] Saved communityNode \(communityId) for content \(contentObject.id)")

        // Write emergence log entry.
        let logEntry = EmergenceLogEntry(
            contentObjectId: contentObject.id,
            communityId: communityId,
            triggerReason: emergenceTriggerReason(for: contentObject)
        )
        try await db
            .collection("contentObjects")
            .document(contentObject.id)
            .collection("emergenceLog")
            .document(logEntry.id)
            .setData(logEntry.firestoreData)

        dlog("[CommunityEmergenceEngine] Emergence log written: \(logEntry.id)")
        return node
    }

    /// Fetches the CommunityNode associated with a specific content object ID, if one exists.
    func fetchCommunityNode(for contentObjectId: String) async throws -> CommunityNode? {
        let snapshot = try await db
            .collection("communityNodes")
            .whereField("contentObjectId", isEqualTo: contentObjectId)
            .limit(to: 1)
            .getDocuments()

        guard let document = snapshot.documents.first else { return nil }
        let data = document.data()
        guard let node = CommunityNode(from: data) else {
            dlog("[CommunityEmergenceEngine] Failed to decode CommunityNode from document \(document.documentID)")
            return nil
        }
        return node
    }

    /// Fetches communities the user is a member of, or communities they might care about,
    /// ordered by lastActiveAt descending.
    func fetchAllNodes(for userId: String, limit: Int) async throws -> [CommunityNode] {
        // Fetch communities where the user is a member by checking the members subcollection.
        // Because Firestore cannot natively join subcollections, we query top-level
        // communityNodes ordered by activity and return the first `limit` results.
        // The full membership-aware query runs server-side via a Cloud Function.
        let snapshot = try await db
            .collection("communityNodes")
            .order(by: "lastActiveAt", descending: true)
            .limit(to: limit)
            .getDocuments()

        let nodes = snapshot.documents.compactMap { doc -> CommunityNode? in
            guard let node = CommunityNode(from: doc.data()) else {
                dlog("[CommunityEmergenceEngine] Skipped undecodable node \(doc.documentID)")
                return nil
            }
            return node
        }
        dlog("[CommunityEmergenceEngine] fetchAllNodes returned \(nodes.count) nodes for user \(userId)")
        return nodes
    }

    /// Records the user as a member of the given community.
    func joinCommunity(communityId: String, userId: String) async throws {
        guard await CommunityOSFlagService.shared.isEnabled(.autoEmergence) else {
            dlog("[CommunityEmergenceEngine] autoEmergence flag is OFF — join blocked")
            return
        }

        let memberData: [String: Any] = [
            "userId": userId,
            "joinedAt": Timestamp(date: Date())
        ]

        try await db
            .collection("communityNodes")
            .document(communityId)
            .collection("members")
            .document(userId)
            .setData(memberData)

        // Increment the memberCount field atomically.
        try await db
            .collection("communityNodes")
            .document(communityId)
            .updateData(["memberCount": FieldValue.increment(Int64(1))])

        dlog("[CommunityEmergenceEngine] User \(userId) joined community \(communityId)")
    }

    /// Removes the user from the community's members subcollection.
    func leaveCommunity(communityId: String, userId: String) async throws {
        try await db
            .collection("communityNodes")
            .document(communityId)
            .collection("members")
            .document(userId)
            .delete()

        try await db
            .collection("communityNodes")
            .document(communityId)
            .updateData(["memberCount": FieldValue.increment(Int64(-1))])

        dlog("[CommunityEmergenceEngine] User \(userId) left community \(communityId)")
    }

    /// Returns true if the user has an active membership record in the community.
    func hasUserJoined(communityId: String, userId: String) async -> Bool {
        do {
            let doc = try await db
                .collection("communityNodes")
                .document(communityId)
                .collection("members")
                .document(userId)
                .getDocument()
            return doc.exists
        } catch {
            dlog("[CommunityEmergenceEngine] hasUserJoined error for \(communityId)/\(userId): \(error)")
            return false
        }
    }

    // MARK: - Private Helpers

    /// Returns true if the content has crossed at least one auto-emergence threshold.
    private func meetsEmergenceThreshold(_ object: ContentObject) -> Bool {
        let meetsDiscussion = object.discussionCount >= CommunityEmergenceThresholds.minDiscussionsForAutoSpace
        let meetsScore = object.communityScore >= CommunityEmergenceThresholds.minEngagementScoreForAutoSpace

        // communityScore encapsulates saves + shares signals server-side.
        // We treat the score gate as the primary signal; discussion count as a secondary confirm.
        let passes = meetsScore || meetsDiscussion
        dlog("[CommunityEmergenceEngine] Threshold check for \(object.id): score=\(object.communityScore) discussions=\(object.discussionCount) passes=\(passes)")
        return passes
    }

    /// Derives a human-readable community name from the content object.
    private func communityName(for object: ContentObject) -> String {
        let title = object.title.trimmingCharacters(in: .whitespacesAndNewlines)
        switch object.kind {
        case .song:
            if let artist = object.metadata["artist"], !artist.isEmpty {
                return "\"\(title)\" by \(artist) Community"
            }
            return "\(title) Community"
        case .bibleVerse:
            return "\(title) Community"
        case .book:
            if let author = object.metadata["author"], !author.isEmpty {
                return "\(title) Readers"
            }
            return "\(title) Readers"
        case .podcast:
            return "\(title) Listeners"
        case .sermon:
            return "\(title) Study Community"
        case .course:
            return "\(title) Learners"
        case .event:
            return "\(title) Community"
        case .prayerRequest:
            return "Prayer Community"
        case .video:
            return "\(title) Watchers"
        case .article:
            return "\(title) Discussion"
        case .testimony:
            return "\(title) Testimony Community"
        case .userPost:
            return "\(title) Community"
        }
    }

    /// Produces a short human-readable string describing which threshold was crossed.
    private func emergenceTriggerReason(for object: ContentObject) -> String {
        var reasons: [String] = []
        if object.communityScore >= CommunityEmergenceThresholds.minEngagementScoreForAutoSpace {
            reasons.append("communityScore=\(String(format: "%.2f", object.communityScore))")
        }
        if object.discussionCount >= CommunityEmergenceThresholds.minDiscussionsForAutoSpace {
            reasons.append("discussionCount=\(object.discussionCount)")
        }
        return reasons.isEmpty ? "threshold_unknown" : reasons.joined(separator: ",")
    }
}
