/**
 * styles.ts — Liquid Glass white/light styles for the Connectors Hub.
 * OWNER: Phase 2 Agent A. All colors derive from the frozen `tokens` (contracts.ts).
 *
 * FORBIDDEN (rejected on sight): cosmic-dark gradients, gold #C9A84C/#FFD97D,
 * purple #7B68EE, Cormorant Garamond.
 */

import React from 'react';
import { tokens } from '../../berean/contracts';

// Semantic status colors (system-native; not in the forbidden set).
export const STATUS_COLORS = {
  ok: '#1A7F4F',
  okDot: '#34C759',
  idleDot: '#AEAEB2',
  error: '#FF3B30',       // ERROR / degraded — red family
  errorBg: '#FFF0EF',
  errorBorder: '#FFD4D1',
  cap: '#B25E00',         // CAP / limit — amber family, VISUALLY DISTINCT from error
  capBg: '#FFF6E9',
  capBorder: '#FFE0B2',
} as const;

export const FONT =
  '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", system-ui, sans-serif';

export const s: Record<string, React.CSSProperties> = {
  screen: {
    backgroundColor: tokens.bg,
    minHeight: '100vh',
    fontFamily: FONT,
    padding: '24px 16px 48px',
    boxSizing: 'border-box',
    color: tokens.text,
  },
  heading: {
    fontSize: 26,
    fontWeight: 700,
    color: tokens.text,
    margin: '0 0 4px',
    letterSpacing: -0.4,
  },
  subheading: {
    fontSize: 14,
    color: tokens.textSub,
    margin: '0 0 22px',
    lineHeight: 1.5,
  },
  // Floating glass card with ambient shadow + backdrop blur.
  card: {
    backgroundColor: tokens.card,
    borderRadius: tokens.radius,
    boxShadow: tokens.shadow,
    padding: '18px 16px',
    marginBottom: 14,
    backdropFilter: 'blur(20px) saturate(180%)',
    WebkitBackdropFilter: 'blur(20px) saturate(180%)',
    border: `1px solid ${tokens.divider}`,
  },
  cardHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  icon: {
    fontSize: 20,
    lineHeight: 1,
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    border: `1px solid ${tokens.divider}`,
    color: tokens.text,
    flexShrink: 0,
  },
  cardTitle: { fontSize: 17, fontWeight: 600, color: tokens.text, flex: 1 },
  tagline: { fontSize: 13, color: tokens.textSub, lineHeight: 1.5, margin: '0 0 14px' },
  rowBetween: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  toggleTrack: (on: boolean): React.CSSProperties => ({
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: on ? STATUS_COLORS.okDot : '#E5E5EA',
    position: 'relative',
    transition: 'background-color .15s',
    cursor: 'pointer',
    border: 'none',
    flexShrink: 0,
  }),
  toggleKnob: (on: boolean): React.CSSProperties => ({
    position: 'absolute',
    top: 2,
    left: on ? 22 : 2,
    width: 26,
    height: 26,
    borderRadius: '50%',
    backgroundColor: '#FFFFFF',
    boxShadow: '0 1px 3px rgba(0,0,0,0.25)',
    transition: 'left .15s',
  }),
  linkRow: {
    display: 'flex',
    gap: 16,
    marginTop: 14,
    flexWrap: 'wrap',
  },
  linkButton: {
    background: 'none',
    border: 'none',
    color: tokens.accent,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
    fontFamily: FONT,
  },
  revokeButton: {
    background: 'none',
    border: 'none',
    color: STATUS_COLORS.error,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
    fontFamily: FONT,
  },
  // Sheets
  sheetBackdrop: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(20,20,20,0.35)',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    zIndex: 1000,
  },
  sheet: {
    backgroundColor: tokens.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    maxWidth: 520,
    maxHeight: '85vh',
    overflowY: 'auto',
    padding: '22px 20px 32px',
    boxShadow: '0 -8px 40px rgba(0,0,0,0.18)',
    backdropFilter: 'blur(24px) saturate(180%)',
    WebkitBackdropFilter: 'blur(24px) saturate(180%)',
  },
  sheetTitle: { fontSize: 20, fontWeight: 700, margin: '0 0 12px', color: tokens.text },
  sheetSectionTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: tokens.textSub,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    margin: '18px 0 8px',
  },
  bullet: { fontSize: 14, color: tokens.text, lineHeight: 1.55, margin: '0 0 6px', paddingLeft: 18, position: 'relative' },
  examplePrompt: {
    fontSize: 14,
    color: tokens.text,
    backgroundColor: tokens.bg,
    borderRadius: 12,
    padding: '10px 12px',
    marginBottom: 8,
    lineHeight: 1.4,
  },
  checkRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    padding: '12px 0',
    borderBottom: `1px solid ${tokens.divider}`,
    cursor: 'pointer',
  },
  checkbox: (on: boolean): React.CSSProperties => ({
    width: 22,
    height: 22,
    borderRadius: 6,
    border: `1.5px solid ${on ? tokens.accent : '#C7C7CC'}`,
    backgroundColor: on ? tokens.accent : 'transparent',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    flexShrink: 0,
    marginTop: 2,
  }),
  checkLabel: { fontSize: 15, fontWeight: 600, color: tokens.text },
  checkHelp: { fontSize: 13, color: tokens.textSub, lineHeight: 1.45, marginTop: 2 },
  primaryButton: (disabled: boolean): React.CSSProperties => ({
    backgroundColor: disabled ? '#E5E5EA' : tokens.accent,
    color: disabled ? '#AEAEB2' : '#FFFFFF',
    border: 'none',
    borderRadius: 14,
    padding: '14px 20px',
    fontSize: 16,
    fontWeight: 600,
    cursor: disabled ? 'not-allowed' : 'pointer',
    width: '100%',
    marginTop: 22,
    fontFamily: FONT,
  }),
  secondaryButton: {
    backgroundColor: 'transparent',
    color: tokens.textSub,
    border: 'none',
    borderRadius: 14,
    padding: '12px 20px',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    width: '100%',
    marginTop: 8,
    fontFamily: FONT,
  },
  expirySelect: {
    width: '100%',
    padding: '12px 14px',
    fontSize: 15,
    borderRadius: 12,
    border: `1px solid ${tokens.divider}`,
    backgroundColor: tokens.bg,
    color: tokens.text,
    fontFamily: FONT,
    marginTop: 8,
  },
  // State blocks
  centerNote: {
    textAlign: 'center',
    color: tokens.textSub,
    fontSize: 14,
    padding: '48px 20px',
    lineHeight: 1.6,
  },
  footerNote: {
    marginTop: 28,
    fontSize: 12,
    color: tokens.textSub,
    textAlign: 'center',
    lineHeight: 1.5,
  },
};
